import { formFor } from "./conjugate";
import { getTense } from "./tenses";
import type { PersonId, TenseId } from "./types";
import { getVerb } from "./verbs";

export interface PhrasePrompt {
  id: string;
  verbId: string;
  tense: TenseId;
  person: PersonId | "forma";
  before: string;
  after: string;
  pt: string;
}

export const PHRASES: PhrasePrompt[] = [
  {
    id: "pedir-pres-yo",
    verbId: "pedir",
    tense: "presente",
    person: "yo",
    before: "En el bar yo ",
    after: " un café con leche.",
    pt: "No bar eu peço um café com leite.",
  },
  {
    id: "pedir-pret-nosotros",
    verbId: "pedir",
    tense: "preterito",
    person: "nosotros",
    before: "Ayer ",
    after: " pizza para toda la familia.",
    pt: "Ontem pedimos pizza para a família toda.",
  },
  {
    id: "hablar-pres-tu",
    verbId: "hablar",
    tense: "presente",
    person: "tu",
    before: "¿",
    after: " español en el trabajo?",
    pt: "Você fala espanhol no trabalho?",
  },
  {
    id: "ser-pres-yo",
    verbId: "ser",
    tense: "presente",
    person: "yo",
    before: "Yo ",
    after: " brasileño y vivo en São Paulo.",
    pt: "Eu sou brasileiro e moro em São Paulo.",
  },
  {
    id: "estar-pres-nosotros",
    verbId: "estar",
    tense: "presente",
    person: "nosotros",
    before: "Hoy ",
    after: " muy cansados.",
    pt: "Hoje estamos muito cansados.",
  },
  {
    id: "ir-pres-yo",
    verbId: "ir",
    tense: "presente",
    person: "yo",
    before: "Después del trabajo ",
    after: " al mercado.",
    pt: "Depois do trabalho eu vou ao mercado.",
  },
  {
    id: "tener-pres-tu",
    verbId: "tener",
    tense: "presente",
    person: "tu",
    before: "¿",
    after: " hambre ahora?",
    pt: "Você está com fome agora?",
  },
  {
    id: "hacer-pret-yo",
    verbId: "hacer",
    tense: "preterito",
    person: "yo",
    before: "Ayer ",
    after: " ejercicio por la mañana.",
    pt: "Ontem eu fiz exercício de manhã.",
  },
  {
    id: "querer-pres-yo",
    verbId: "querer",
    tense: "presente",
    person: "yo",
    before: "Yo ",
    after: " aprender más verbos.",
    pt: "Eu quero aprender mais verbos.",
  },
  {
    id: "poder-pres-tu",
    verbId: "poder",
    tense: "presente",
    person: "tu",
    before: "¿",
    after: " ayudarme un momento?",
    pt: "Você pode me ajudar um momento?",
  },
  {
    id: "decir-pret-el",
    verbId: "decir",
    tense: "preterito",
    person: "el",
    before: "Ella me ",
    after: " la verdad ayer.",
    pt: "Ela me disse a verdade ontem.",
  },
  {
    id: "venir-pres-tu",
    verbId: "venir",
    tense: "presente",
    person: "tu",
    before: "¿",
    after: " con nosotros al cine?",
    pt: "Você vem com a gente ao cinema?",
  },
  {
    id: "salir-fut-nosotros",
    verbId: "salir",
    tense: "futuro",
    person: "nosotros",
    before: "Mañana ",
    after: " más temprano.",
    pt: "Amanhã sairemos mais cedo.",
  },
  {
    id: "poner-pret-tu",
    verbId: "poner",
    tense: "preterito",
    person: "tu",
    before: "¿Dónde ",
    after: " las llaves?",
    pt: "Onde você pôs as chaves?",
  },
  {
    id: "saber-pres-yo",
    verbId: "saber",
    tense: "presente",
    person: "yo",
    before: "Yo ",
    after: " un poco de español.",
    pt: "Eu sei um pouco de espanhol.",
  },
  {
    id: "conocer-pres-yo",
    verbId: "conocer",
    tense: "presente",
    person: "yo",
    before: "Yo ",
    after: " esta ciudad muy bien.",
    pt: "Eu conheço esta cidade muito bem.",
  },
  {
    id: "llegar-pret-yo",
    verbId: "llegar",
    tense: "preterito",
    person: "yo",
    before: "Ayer ",
    after: " tarde al trabajo.",
    pt: "Ontem cheguei tarde no trabalho.",
  },
  {
    id: "volver-pres-yo",
    verbId: "volver",
    tense: "presente",
    person: "yo",
    before: "Normalmente ",
    after: " a casa a las seis.",
    pt: "Normalmente eu volto para casa às seis.",
  },
  {
    id: "dormir-pret-yo",
    verbId: "dormir",
    tense: "preterito",
    person: "yo",
    before: "Anoche ",
    after: " muy bien.",
    pt: "Ontem à noite eu dormi muito bem.",
  },
  {
    id: "pensar-pres-tu",
    verbId: "pensar",
    tense: "presente",
    person: "tu",
    before: "¿Qué ",
    after: " de esta idea?",
    pt: "O que você acha desta ideia?",
  },
  {
    id: "empezar-pres-nosotros",
    verbId: "empezar",
    tense: "presente",
    person: "nosotros",
    before: "Nosotros ",
    after: " la clase a las nueve.",
    pt: "Nós começamos a aula às nove.",
  },
  {
    id: "necesitar-pres-yo",
    verbId: "necesitar",
    tense: "presente",
    person: "yo",
    before: "Hoy ",
    after: " tu ayuda, por favor.",
    pt: "Hoje eu preciso da sua ajuda, por favor.",
  },
  {
    id: "llamar-fut-yo",
    verbId: "llamar",
    tense: "futuro",
    person: "yo",
    before: "Te ",
    after: " esta noche.",
    pt: "Eu te ligarei esta noite.",
  },
  {
    id: "comer-pret-nosotros",
    verbId: "comer",
    tense: "preterito",
    person: "nosotros",
    before: "Ayer ",
    after: " en un restaurante cerca.",
    pt: "Ontem comemos num restaurante perto.",
  },
  {
    id: "vivir-pres-yo",
    verbId: "vivir",
    tense: "presente",
    person: "yo",
    before: "Yo ",
    after: " cerca del mar.",
    pt: "Eu moro perto do mar.",
  },
  {
    id: "ver-perfecto-tu",
    verbId: "ver",
    tense: "perfecto",
    person: "tu",
    before: "¿",
    after: " mis gafas?",
    pt: "Você viu (tem visto) meus óculos?",
  },
  {
    id: "ir-imperfecto-nosotros",
    verbId: "ir",
    tense: "imperfecto",
    person: "nosotros",
    before: "De niños ",
    after: " al parque todos los domingos.",
    pt: "Quando crianças íamos ao parque todos os domingos.",
  },
  {
    id: "hacer-cond-yo",
    verbId: "hacer",
    tense: "condicional",
    person: "yo",
    before: "Yo ",
    after: " la cena si tuviera tiempo.",
    pt: "Eu faria o jantar se tivesse tempo.",
  },
  {
    id: "venir-subj-tu",
    verbId: "venir",
    tense: "subjuntivo",
    person: "tu",
    before: "Espero que ",
    after: " mañana a la fiesta.",
    pt: "Espero que você venha amanhã à festa.",
  },
  {
    id: "decir-imp-tu",
    verbId: "decir",
    tense: "imperativo",
    person: "tu",
    before: "Por favor, ",
    after: " la verdad.",
    pt: "Por favor, diga a verdade.",
  },
  {
    id: "pedir-ger",
    verbId: "pedir",
    tense: "gerundio",
    person: "forma",
    before: "Estoy ",
    after: " la cuenta.",
    pt: "Estou pedindo a conta.",
  },
  {
    id: "escribir-part",
    verbId: "escribir",
    tense: "participio",
    person: "forma",
    before: "He ",
    after: " tres mensajes.",
    pt: "Escrevi (tenho escrito) três mensagens.",
  },
  {
    id: "dar-pret-ellos",
    verbId: "dar",
    tense: "preterito",
    person: "ellos",
    before: "Ellos nos ",
    after: " las llaves de la casa.",
    pt: "Eles nos deram as chaves da casa.",
  },
  {
    id: "trabajar-imperf-yo",
    verbId: "trabajar",
    tense: "imperfecto",
    person: "yo",
    before: "Antes ",
    after: " en un café.",
    pt: "Antes eu trabalhava num café.",
  },
];

export function expectedFor(phrase: PhrasePrompt): string {
  return formFor(getVerb(phrase.verbId), phrase.tense, phrase.person);
}

export function phrasesForTense(tenseId: TenseId | "all"): PhrasePrompt[] {
  if (tenseId === "all") return PHRASES;
  return PHRASES.filter((item) => item.tense === tenseId);
}

export function tenseLabelFor(phrase: PhrasePrompt): string {
  return getTense(phrase.tense).nameEs;
}
