import { formFor } from "./conjugate";
import { getTense } from "./tenses";
import type { PersonId, TenseId } from "./types";
import { getVerb } from "./verbs";

export interface PhrasePrompt {
  id: string;
  verbId: string;
  tense: TenseId;
  person: PersonId | "forma";
  before: string;
  after: string;
  pt: string;
}

export const PHRASES: PhrasePrompt[] = [
  {
    id: "pedir-pres-yo",
    verbId: "pedir",
    tense: "presente",
    person: "yo",
    before: "En el bar yo ",
    after: " un café con leche.",
    pt: "No bar eu peço um café com leite.",
  },
  {
    id: "pedir-pret-nosotros",
    verbId: "pedir",
    tense: "preterito",
    person: "nosotros",
    before: "Ayer ",
    after: " pizza para toda la familia.",
    pt: "Ontem pedimos pizza para a família toda.",
  },
  {
    id: "hablar-pres-tu",
    verbId: "hablar",
    tense: "presente",
    person: "tu",
    before: "¿",
    after: " español en el trabajo?",
    pt: "Você fala espanhol no trabalho?",
  },
  {
    id: "ser-pres-yo",
    verbId: "ser",
    tense: "presente",
    person: "yo",
    before: "Yo ",
    after: " brasileño y vivo en São Paulo.",
    pt: "Eu sou brasileiro e moro em São Paulo.",
  },
  {
    id: "estar-pres-nosotros",
    verbId: "estar",
    tense: "presente",
    person: "nosotros",
    before: "Hoy ",
    after: " muy cansados.",
    pt: "Hoje estamos muito cansados.",
  },
  {
    id: "ir-pres-yo",
    verbId: "ir",
    tense: "presente",
    person: "yo",
    before: "Después del trabajo ",
    after: " al mercado.",
    pt: "Depois do trabalho eu vou ao mercado.",
  },
  {
    id: "tener-pres-tu",
    verbId: "tener",
    tense: "presente",
    person: "tu",
    before: "¿",
    after: " hambre ahora?",
    pt: "Você está com fome agora?",
  },
  {
    id: "hacer-pret-yo",
    verbId: "hacer",
    tense: "preterito",
    person: "yo",
    before: "Ayer ",
    after: " ejercicio por la mañana.",
    pt: "Ontem eu fiz exercício de manhã.",
  },
  {
    id: "querer-pres-yo",
    verbId: "querer",
    tense: "presente",
    person: "yo",
    before: "Yo ",
    after: " aprender más verbos.",
    pt: "Eu quero aprender mais verbos.",
  },
  {
    id: "poder-pres-tu",
    verbId: "poder",
    tense: "presente",
    person: "tu",
    before: "¿",
    after: " ayudarme un momento?",
    pt: "Você pode me ajudar um momento?",
  },
  {
    id: "decir-pret-el",
    verbId: "decir",
    tense: "preterito",
    person: "el",
    before: "Ella me ",
    after: " la verdad ayer.",
    pt: "Ela me disse a verdade ontem.",
  },
  {
    id: "venir-pres-tu",
    verbId: "venir",
    tense: "presente",
    person: "tu",
    before: "¿",
    after: " con nosotros al cine?",
    pt: "Você vem com a gente ao cinema?",
  },
  {
    id: "salir-fut-nosotros",
    verbId: "salir",
    tense: "futuro",
    person: "nosotros",
    before: "Mañana ",
    after: " más temprano.",
    pt: "Amanhã sairemos mais cedo.",
  },
  {
    id: "poner-pret-tu",
    verbId: "poner",
    tense: "preterito",
    person: "tu",
    before: "¿Dónde ",
    after: " las llaves?",
    pt: "Onde você pôs as chaves?",
  },
  {
    id: "saber-pres-yo",
    verbId: "saber",
    tense: "presente",
    person: "yo",
    before: "Yo ",
    after: " un poco de español.",
    pt: "Eu sei um pouco de espanhol.",
  },
  {
    id: "conocer-pres-yo",
    verbId: "conocer",
    tense: "presente",
    person: "yo",
    before: "Yo ",
    after: " esta ciudad muy bien.",
    pt: "Eu conheço esta cidade muito bem.",
  },
  {
    id: "llegar-pret-yo",
    verbId: "llegar",
    tense: "preterito",
    person: "yo",
    before: "Ayer ",
    after: " tarde al trabajo.",
    pt: "Ontem cheguei tarde no trabalho.",
  },
  {
    id: "volver-pres-yo",
    verbId: "volver",
    tense: "presente",
    person: "yo",
    before: "Normalmente ",
    after: " a casa a las seis.",
    pt: "Normalmente eu volto para casa às seis.",
  },
  {
    id: "dormir-pret-yo",
    verbId: "dormir",
    tense: "preterito",
    person: "yo",
    before: "Anoche ",
    after: " muy bien.",
    pt: "Ontem à noite eu dormi muito bem.",
  },
  {
    id: "pensar-pres-tu",
    verbId: "pensar",
    tense: "presente",
    person: "tu",
    before: "¿Qué ",
    after: " de esta idea?",
    pt: "O que você acha desta ideia?",
  },
  {
    id: "empezar-pres-nosotros",
    verbId: "empezar",
    tense: "presente",
    person: "nosotros",
    before: "Nosotros ",
    after: " la clase a las nueve.",
    pt: "Nós começamos a aula às nove.",
  },
  {
    id: "necesitar-pres-yo",
    verbId: "necesitar",
    tense: "presente",
    person: "yo",
    before: "Hoy ",
    after: " tu ayuda, por favor.",
    pt: "Hoje eu preciso da sua ajuda, por favor.",
  },
  {
    id: "llamar-fut-yo",
    verbId: "llamar",
    tense: "futuro",
    person: "yo",
    before: "Te ",
    after: " esta noche.",
    pt: "Eu te ligarei esta noite.",
  },
  {
    id: "comer-pret-nosotros",
    verbId: "comer",
    tense: "preterito",
    person: "nosotros",
    before: "Ayer ",
    after: " en un restaurante cerca.",
    pt: "Ontem comemos num restaurante perto.",
  },
  {
    id: "vivir-pres-yo",
    verbId: "vivir",
    tense: "presente",
    person: "yo",
    before: "Yo ",
    after: " cerca del mar.",
    pt: "Eu moro perto do mar.",
  },
  {
    id: "ver-perfecto-tu",
    verbId: "ver",
    tense: "perfecto",
    person: "tu",
    before: "¿",
    after: " mis gafas?",
    pt: "Você viu (tem visto) meus óculos?",
  },
  {
    id: "ir-imperfecto-nosotros",
    verbId: "ir",
    tense: "imperfecto",
    person: "nosotros",
    before: "De niños ",
    after: " al parque todos los domingos.",
    pt: "Quando crianças íamos ao parque todos os domingos.",
  },
  {
    id: "hacer-cond-yo",
    verbId: "hacer",
    tense: "condicional",
    person: "yo",
    before: "Yo ",
    after: " la cena si tuviera tiempo.",
    pt: "Eu faria o jantar se tivesse tempo.",
  },
  {
    id: "venir-subj-tu",
    verbId: "venir",
    tense: "subjuntivo",
    person: "tu",
    before: "Espero que ",
    after: " mañana a la fiesta.",
    pt: "Espero que você venha amanhã à festa.",
  },
  {
    id: "decir-imp-tu",
    verbId: "decir",
    tense: "imperativo",
    person: "tu",
    before: "Por favor, ",
    after: " la verdad.",
    pt: "Por favor, diga a verdade.",
  },
  {
    id: "pedir-ger",
    verbId: "pedir",
    tense: "gerundio",
    person: "forma",
    before: "Estoy ",
    after: " la cuenta.",
    pt: "Estou pedindo a conta.",
  },
  {
    id: "escribir-part",
    verbId: "escribir",
    tense: "participio",
    person: "forma",
    before: "He ",
    after: " tres mensajes.",
    pt: "Escrevi (tenho escrito) três mensagens.",
  },
  {
    id: "dar-pret-ellos",
    verbId: "dar",
    tense: "preterito",
    person: "ellos",
    before: "Ellos nos ",
    after: " las llaves de la casa.",
    pt: "Eles nos deram as chaves da casa.",
  },
  {
    id: "trabajar-imperf-yo",
    verbId: "trabajar",
    tense: "imperfecto",
    person: "yo",
    before: "Antes ",
    after: " en un café.",
    pt: "Antes eu trabalhava num café.",
  },
  {
    id: "comer-imperf-ellos",
    verbId: "comer",
    tense: "imperfecto",
    person: "ellos",
    before: "De niños ellos ",
    after: " mucho chocolate.",
    pt: "Quando crianças eles comiam muito chocolate.",
  },
  {
    id: "vivir-imperf-tu",
    verbId: "vivir",
    tense: "imperfecto",
    person: "tu",
    before: "Cuando eras pequeña, ",
    after: " cerca de la playa.",
    pt: "Quando você era pequena, morava perto da praia.",
  },
  {
    id: "tener-fut-ellos",
    verbId: "tener",
    tense: "futuro",
    person: "ellos",
    before: "El año que viene ellos ",
    after: " una casa nueva.",
    pt: "No ano que vem eles terão uma casa nova.",
  },
  {
    id: "poder-cond-yo",
    verbId: "poder",
    tense: "condicional",
    person: "yo",
    before: "Yo ",
    after: " ayudarte mañana.",
    pt: "Eu poderia te ajudar amanhã.",
  },
  {
    id: "querer-cond-nosotros",
    verbId: "querer",
    tense: "condicional",
    person: "nosotros",
    before: "Nosotros ",
    after: " un café, por favor.",
    pt: "Nós gostaríamos de um café, por favor.",
  },
  {
    id: "hacer-plusc-yo",
    verbId: "hacer",
    tense: "pluscuamperfecto",
    person: "yo",
    before: "Cuando llegaste, yo ya ",
    after: " la cena.",
    pt: "Quando você chegou, eu já tinha feito o jantar.",
  },
  {
    id: "ver-plusc-ellos",
    verbId: "ver",
    tense: "pluscuamperfecto",
    person: "ellos",
    before: "Ellos nunca ",
    after: " la nieve.",
    pt: "Eles nunca tinham visto a neve.",
  },
  {
    id: "escribir-perfecto-yo",
    verbId: "escribir",
    tense: "perfecto",
    person: "yo",
    before: "Hoy ",
    after: " tres correos.",
    pt: "Hoje eu escrevi (tenho escrito) três e-mails.",
  },
  {
    id: "ir-subj-nosotros",
    verbId: "ir",
    tense: "subjuntivo",
    person: "nosotros",
    before: "Quiero que ",
    after: " juntos al cine.",
    pt: "Quero que a gente vá juntos ao cinema.",
  },
  {
    id: "estar-subj-el",
    verbId: "estar",
    tense: "subjuntivo",
    person: "el",
    before: "Espero que ella ",
    after: " bien.",
    pt: "Espero que ela esteja bem.",
  },
  {
    id: "hablar-imperfsubj-yo",
    verbId: "hablar",
    tense: "imperfecto_subj",
    person: "yo",
    before: "Si yo ",
    after: " mejor español, viajaría más.",
    pt: "Se eu falasse melhor espanhol, viajaria mais.",
  },
  {
    id: "tener-imperfsubj-tu",
    verbId: "tener",
    tense: "imperfecto_subj",
    person: "tu",
    before: "Si ",
    after: " tiempo, iríamos al mar.",
    pt: "Se você tivesse tempo, iríamos ao mar.",
  },
  {
    id: "salir-imp-tu",
    verbId: "salir",
    tense: "imperativo",
    person: "tu",
    before: "¡",
    after: " ahora mismo!",
    pt: "Saia agora mesmo!",
  },
  {
    id: "venir-imp-tu",
    verbId: "venir",
    tense: "imperativo",
    person: "tu",
    before: "¡",
    after: " conmigo, por favor!",
    pt: "Venha comigo, por favor!",
  },
  {
    id: "comer-impneg-tu",
    verbId: "comer",
    tense: "imperativo_neg",
    person: "tu",
    before: "Por favor, ",
    after: " tan rápido.",
    pt: "Por favor, não coma tão rápido.",
  },
  {
    id: "ir-impneg-tu",
    verbId: "ir",
    tense: "imperativo_neg",
    person: "tu",
    before: "Por favor, ",
    after: " todavía.",
    pt: "Por favor, não vá ainda.",
  },
  {
    id: "dormir-ger",
    verbId: "dormir",
    tense: "gerundio",
    person: "forma",
    before: "El bebé está ",
    after: ".",
    pt: "O bebê está dormindo.",
  },
  {
    id: "leer-ger",
    verbId: "leer",
    tense: "gerundio",
    person: "forma",
    before: "Ella está ",
    after: " un libro.",
    pt: "Ela está lendo um livro.",
  },
  {
    id: "volver-part",
    verbId: "volver",
    tense: "participio",
    person: "forma",
    before: "Todavía no he ",
    after: " a casa.",
    pt: "Ainda não voltei para casa.",
  },
  {
    id: "poner-part",
    verbId: "poner",
    tense: "participio",
    person: "forma",
    before: "¿Dónde has ",
    after: " las llaves?",
    pt: "Onde você pôs as chaves?",
  },
  {
    id: "decir-fut-yo",
    verbId: "decir",
    tense: "futuro",
    person: "yo",
    before: "Mañana te ",
    after: " la verdad.",
    pt: "Amanhã eu te direi a verdade.",
  },
  {
    id: "saber-fut-nosotros",
    verbId: "saber",
    tense: "futuro",
    person: "nosotros",
    before: "Pronto ",
    after: " el resultado.",
    pt: "Logo saberemos o resultado.",
  },
  {
    id: "pedir-subj-el",
    verbId: "pedir",
    tense: "subjuntivo",
    person: "el",
    before: "Quiero que él ",
    after: " la cuenta.",
    pt: "Quero que ele peça a conta.",
  },
  {
    id: "empezar-pret-yo",
    verbId: "empezar",
    tense: "preterito",
    person: "yo",
    before: "Ayer ",
    after: " a estudiar a las siete.",
    pt: "Ontem comecei a estudar às sete.",
  },
  {
    id: "conocer-pret-nosotros",
    verbId: "conocer",
    tense: "preterito",
    person: "nosotros",
    before: "El verano pasado ",
    after: " Madrid.",
    pt: "No verão passado conhecemos Madrid.",
  },
  {
    id: "llegar-fut-tu",
    verbId: "llegar",
    tense: "futuro",
    person: "tu",
    before: "¿A qué hora ",
    after: " a casa?",
    pt: "A que horas você chegará em casa?",
  },
  {
    id: "necesitar-cond-yo",
    verbId: "necesitar",
    tense: "condicional",
    person: "yo",
    before: "Yo ",
    after: " más tiempo para esto.",
    pt: "Eu precisaria de mais tempo para isto.",
  },
  {
    id: "abrir-perfecto-ellos",
    verbId: "abrir",
    tense: "perfecto",
    person: "ellos",
    before: "Ellos ya ",
    after: " la tienda.",
    pt: "Eles já abriram a loja.",
  },
  {
    id: "ser-imperf-el",
    verbId: "ser",
    tense: "imperfecto",
    person: "el",
    before: "Ella ",
    after: " médica en aquel pueblo.",
    pt: "Ela era médica naquele povoado.",
  },
];

export function expectedFor(phrase: PhrasePrompt): string {
  return formFor(getVerb(phrase.verbId), phrase.tense, phrase.person);
}

export function phrasesForTense(tenseId: TenseId | "all"): PhrasePrompt[] {
  if (tenseId === "all") return PHRASES;
  return PHRASES.filter((item) => item.tense === tenseId);
}

export function tenseLabelFor(phrase: PhrasePrompt): string {
  return getTense(phrase.tense).nameEs;
}

export function phraseStats(list: PhrasePrompt[] = PHRASES): { count: number; tenses: number } {
  return { count: list.length, tenses: new Set(list.map((item) => item.tense)).size };
}
