import { normalizeAnswer, stripDiacritics } from "./conjugate";
import type { CheckResult } from "./types";

export type PrepId =
  | "a"
  | "al"
  | "de"
  | "del"
  | "en"
  | "con"
  | "sin"
  | "por"
  | "para"
  | "entre"
  | "hasta"
  | "desde"
  | "sobre"
  | "durante"
  | "hacia"
  | "según";

export type PrepGroupId = "por-para" | "a-en-de" | "con-sin" | "otras" | "articulo";

export interface PrepMeta {
  id: PrepId;
  group: PrepGroupId;
  label: string;
  meaningPt: string;
}

export interface PrepPrompt {
  id: string;
  prep: PrepId;
  use: string;
  before: string;
  after: string;
  pt: string;
  why: string;
  fill?: string;
  aliases?: string[];
}

export const PREP_GROUPS: { id: PrepGroupId; label: string }[] = [
  { id: "por-para", label: "por / para" },
  { id: "a-en-de", label: "a / en / de" },
  { id: "articulo", label: "por la / en el / a las" },
  { id: "con-sin", label: "con / sin" },
  { id: "otras", label: "outras" },
];

export const PREPOSITIONS: PrepMeta[] = [
  { id: "a", group: "a-en-de", label: "a", meaningPt: "a / para (direção)" },
  { id: "al", group: "a-en-de", label: "al", meaningPt: "ao (a + el)" },
  { id: "de", group: "a-en-de", label: "de", meaningPt: "de / desde" },
  { id: "del", group: "a-en-de", label: "del", meaningPt: "do (de + el)" },
  { id: "en", group: "a-en-de", label: "en", meaningPt: "em / no" },
  { id: "con", group: "con-sin", label: "con", meaningPt: "com" },
  { id: "sin", group: "con-sin", label: "sin", meaningPt: "sem" },
  { id: "por", group: "por-para", label: "por", meaningPt: "por (causa, duração, caminho)" },
  { id: "para", group: "por-para", label: "para", meaningPt: "para (fim, prazo, destinatário)" },
  { id: "entre", group: "otras", label: "entre", meaningPt: "entre" },
  { id: "hasta", group: "otras", label: "hasta", meaningPt: "até" },
  { id: "desde", group: "otras", label: "desde", meaningPt: "desde / a partir de" },
  { id: "sobre", group: "otras", label: "sobre", meaningPt: "sobre / em cima de" },
  { id: "durante", group: "otras", label: "durante", meaningPt: "durante" },
  { id: "hacia", group: "otras", label: "hacia", meaningPt: "em direção a" },
  { id: "según", group: "otras", label: "según", meaningPt: "segundo / de acordo com" },
];

export const PREP_PROMPTS: PrepPrompt[] = [
  {
    id: "para-ti",
    prep: "para",
    use: "destinatário",
    before: "Este café es ",
    after: " ti.",
    pt: "Este café é para você.",
    why: "Destinatário: a coisa é para alguém.",
  },
  {
    id: "para-examen",
    prep: "para",
    use: "finalidade",
    before: "Estudio ",
    after: " el examen.",
    pt: "Estudo para a prova.",
    why: "Finalidade: estudo com um objetivo.",
  },
  {
    id: "para-manana",
    prep: "para",
    use: "prazo",
    before: "Necesito el informe ",
    after: " mañana.",
    pt: "Preciso do relatório para amanhã.",
    why: "Prazo: até quando precisa estar pronto.",
  },
  {
    id: "para-empresa",
    prep: "para",
    use: "trabalho",
    before: "Trabajo ",
    after: " una empresa brasileña.",
    pt: "Trabalho para uma empresa brasileira.",
    why: "Para quem você trabalha (empresa, pessoa).",
  },
  {
    id: "para-llevar",
    prep: "para",
    use: "finalidade",
    before: "¿Esto es para aquí o ",
    after: " llevar?",
    pt: "Isto é para comer aqui ou para levar?",
    why: "Finalidade: para levar.",
  },
  {
    id: "para-leer",
    prep: "para",
    use: "finalidade",
    before: "Estas gafas son ",
    after: " leer.",
    pt: "Estes óculos são para ler.",
    why: "Para + infinitivo: propósito.",
  },
  {
    id: "para-sevilla",
    prep: "para",
    use: "destino",
    before: "El tren sale ",
    after: " Sevilla.",
    pt: "O trem sai para Sevilha.",
    why: "Destino de um meio de transporte que parte.",
  },
  {
    id: "por-gracias",
    prep: "por",
    use: "causa",
    before: "Gracias ",
    after: " tu ayuda.",
    pt: "Obrigado pela sua ajuda.",
    why: "Causa: agradecer por algo.",
  },
  {
    id: "por-parque",
    prep: "por",
    use: "caminho",
    fill: "por el",
    before: "Caminamos ",
    after: " parque.",
    pt: "Caminhamos pelo parque.",
    why: "por + el: movimento através de um lugar.",
  },
  {
    id: "por-telefono",
    prep: "por",
    use: "meio",
    before: "Te llamo ",
    after: " teléfono.",
    pt: "Te ligo por telefone.",
    why: "Meio: como a ação acontece.",
  },
  {
    id: "por-manana",
    prep: "por",
    use: "tempo",
    fill: "por la",
    before: "Trabajo ",
    after: " mañana.",
    pt: "Trabalho de manhã.",
    why: "Parte do dia: por la mañana / tarde / noche.",
  },
  {
    id: "por-horas",
    prep: "por",
    use: "duração",
    before: "Estuve allí ",
    after: " dos horas.",
    pt: "Fiquei lá por duas horas.",
    why: "Duração: por quanto tempo.",
  },
  {
    id: "por-precio",
    prep: "por",
    use: "troca",
    before: "Lo compré ",
    after: " diez euros.",
    pt: "Comprei por dez euros.",
    why: "Troca: preço, em troca de.",
  },
  {
    id: "por-ti",
    prep: "por",
    use: "causa",
    before: "Lo hice ",
    after: " ti.",
    pt: "Fiz isso por você.",
    why: "Causa ou favor: por alguém.",
  },
  {
    id: "por-gusto",
    prep: "por",
    use: "causa",
    before: "Estudio español ",
    after: " gusto.",
    pt: "Estudo espanhol por gosto.",
    why: "Motivo: por que você faz isso.",
  },
  {
    id: "a-casa",
    prep: "a",
    use: "destino",
    before: "Después del trabajo voy ",
    after: " casa.",
    pt: "Depois do trabalho vou para casa.",
    why: "Direção: ir a um lugar (movimento).",
  },
  {
    id: "al-medico",
    prep: "al",
    use: "destino",
    before: "Mañana voy ",
    after: " médico.",
    pt: "Amanhã vou ao médico.",
    why: "a + el = al.",
    aliases: ["a el"],
  },
  {
    id: "a-las-ocho",
    prep: "a",
    use: "tempo",
    fill: "a las",
    before: "Llegamos ",
    after: " ocho.",
    pt: "Chegamos às oito.",
    why: "Hora do relógio: a las + hora.",
  },
  {
    id: "a-maria",
    prep: "a",
    use: "pessoa",
    before: "Invito ",
    after: " María a la cena.",
    pt: "Convido a María para o jantar.",
    why: "a pessoal: objeto direto de pessoa.",
  },
  {
    id: "a-playa",
    prep: "a",
    use: "destino",
    fill: "a la",
    before: "El sábado vamos ",
    after: " playa.",
    pt: "Sábado vamos à praia.",
    why: "Direção com artigo feminino: a la.",
  },
  {
    id: "a-pie",
    prep: "a",
    use: "meio",
    before: "Voy ",
    after: " pie hasta el metro.",
    pt: "Vou a pé até o metrô.",
    why: "Meio: a pie, a caballo.",
  },
  {
    id: "empezar-a",
    prep: "a",
    use: "verbo",
    before: "Empiezo ",
    after: " trabajar a las nueve.",
    pt: "Começo a trabalhar às nove.",
    why: "empezar a + infinitivo.",
  },
  {
    id: "en-casa",
    prep: "en",
    use: "lugar",
    before: "Hoy estoy ",
    after: " casa.",
    pt: "Hoje estou em casa.",
    why: "Estar em um lugar (sem movimento).",
  },
  {
    id: "en-madrid",
    prep: "en",
    use: "lugar",
    before: "Vivo ",
    after: " Madrid.",
    pt: "Moro em Madrid.",
    why: "Cidade ou país em que se está / mora: en.",
  },
  {
    id: "en-mesa",
    prep: "en",
    use: "lugar",
    fill: "en la",
    before: "El libro está ",
    after: " mesa.",
    pt: "O livro está na mesa.",
    why: "en + la: posição, lugar parado.",
  },
  {
    id: "en-invierno",
    prep: "en",
    use: "tempo",
    before: "",
    after: " invierno hace frío.",
    pt: "No inverno faz frio.",
    why: "Estação, mês ou ano: en enero, en 2020.",
  },
  {
    id: "en-ti",
    prep: "en",
    use: "verbo",
    before: "Pienso ",
    after: " ti todo el día.",
    pt: "Penso em você o dia todo.",
    why: "pensar en alguien.",
  },
  {
    id: "en-tienda",
    prep: "en",
    use: "lugar",
    fill: "en la",
    before: "Entramos ",
    after: " tienda.",
    pt: "Entramos na loja.",
    why: "entrar en + artigo.",
  },
  {
    id: "en-metro",
    prep: "en",
    use: "meio",
    before: "Voy al trabajo ",
    after: " metro.",
    pt: "Vou ao trabalho de metrô.",
    why: "Meio fechado: en metro, en tren, en coche.",
  },
  {
    id: "de-brasil",
    prep: "de",
    use: "origem",
    before: "Soy ",
    after: " Brasil.",
    pt: "Sou do Brasil.",
    why: "Origem: ser de um lugar.",
  },
  {
    id: "de-padre",
    prep: "de",
    use: "posse",
    before: "El coche ",
    after: " mi padre es azul.",
    pt: "O carro do meu pai é azul.",
    why: "Posse: de alguém.",
  },
  {
    id: "de-cafe",
    prep: "de",
    use: "conteúdo",
    before: "Una taza ",
    after: " café, por favor.",
    pt: "Uma xícara de café, por favor.",
    why: "Conteúdo ou material: de café, de madera.",
  },
  {
    id: "del-trabajo",
    prep: "del",
    use: "origem",
    before: "Salgo ",
    after: " trabajo a las seis.",
    pt: "Saio do trabalho às seis.",
    why: "de + el = del.",
    aliases: ["de el"],
  },
  {
    id: "de-pelicula",
    prep: "de",
    use: "tema",
    fill: "de la",
    before: "Hablamos ",
    after: " película.",
    pt: "Falamos do filme.",
    why: "hablar de + artigo.",
  },
  {
    id: "de-estacion",
    prep: "de",
    use: "lugar",
    fill: "de la",
    before: "Estoy cerca ",
    after: " estación.",
    pt: "Estou perto da estação.",
    why: "cerca de + artigo feminino: de la.",
  },
  {
    id: "de-casa",
    prep: "de",
    use: "origem",
    before: "¿A qué hora sales ",
    after: " casa?",
    pt: "A que horas você sai de casa?",
    why: "Sair de um lugar: salir de.",
  },
  {
    id: "con-leche",
    prep: "con",
    use: "companhia",
    before: "Un café ",
    after: " leche, por favor.",
    pt: "Um café com leite, por favor.",
    why: "Com: acompanhado de.",
  },
  {
    id: "con-amigos",
    prep: "con",
    use: "companhia",
    before: "El viernes salgo ",
    after: " mis amigos.",
    pt: "Sexta saio com meus amigos.",
    why: "Companhia de pessoas.",
  },
  {
    id: "con-hermana",
    prep: "con",
    use: "companhia",
    before: "Hablo ",
    after: " mi hermana todos los días.",
    pt: "Falo com a minha irmã todos os dias.",
    why: "hablar con alguien.",
  },
  {
    id: "con-queso",
    prep: "con",
    use: "companhia",
    before: "Quiero un bocadillo ",
    after: " queso.",
    pt: "Quero um sanduíche com queijo.",
    why: "Ingrediente ou acompanhamento.",
  },
  {
    id: "sin-azucar",
    prep: "sin",
    use: "ausência",
    before: "Un café ",
    after: " azúcar, por favor.",
    pt: "Um café sem açúcar, por favor.",
    why: "Sem: ausência de algo.",
  },
  {
    id: "sin-paraguas",
    prep: "sin",
    use: "ausência",
    before: "Salí ",
    after: " paraguas y me mojé.",
    pt: "Saí sem guarda-chuva e me molhei.",
    why: "Fazer algo sem ter algo.",
  },
  {
    id: "sin-musica",
    prep: "sin",
    use: "ausência",
    before: "No puedo vivir ",
    after: " música.",
    pt: "Não posso viver sem música.",
    why: "sin + substantivo.",
  },
  {
    id: "entre-tiendas",
    prep: "entre",
    use: "lugar",
    before: "El banco está ",
    after: " la farmacia y el café.",
    pt: "O banco fica entre a farmácia e o café.",
    why: "Entre dois pontos.",
  },
  {
    id: "entre-dias",
    prep: "entre",
    use: "tempo",
    before: "",
    after: " lunes y viernes trabajo.",
    pt: "Entre segunda e sexta eu trabalho.",
    why: "Intervalo: entre A y B.",
  },
  {
    id: "hasta-manana",
    prep: "hasta",
    use: "tempo",
    before: "",
    after: " mañana.",
    pt: "Até amanhã.",
    why: "Limite no tempo: até quando.",
  },
  {
    id: "hasta-seis",
    prep: "hasta",
    use: "tempo",
    fill: "hasta las",
    before: "Hoy trabajo ",
    after: " seis.",
    pt: "Hoje trabalho até as seis.",
    why: "hasta + las: até que hora.",
  },
  {
    id: "desde-ocho",
    prep: "desde",
    use: "tempo",
    fill: "desde las",
    before: "Espero ",
    after: " ocho.",
    pt: "Espero desde as oito.",
    why: "desde + las: a partir de que hora.",
  },
  {
    id: "desde-2020",
    prep: "desde",
    use: "tempo",
    before: "Vivo aquí ",
    after: " 2020.",
    pt: "Moro aqui desde 2020.",
    why: "Desde quando algo começou.",
  },
  {
    id: "sobre-espana",
    prep: "sobre",
    use: "tema",
    before: "Estoy leyendo un libro ",
    after: " España.",
    pt: "Estou lendo um livro sobre a Espanha.",
    why: "Tema: sobre algo.",
  },
  {
    id: "sobre-mesa",
    prep: "sobre",
    use: "lugar",
    fill: "sobre la",
    before: "Dejé las llaves ",
    after: " mesa.",
    pt: "Deixei as chaves sobre a mesa.",
    why: "sobre + la: em cima da superfície.",
  },
  {
    id: "durante-cena",
    prep: "durante",
    use: "tempo",
    fill: "durante la",
    before: "",
    after: " cena no uso el móvil.",
    pt: "Durante o jantar não uso o celular.",
    why: "durante + la: enquanto isso acontece.",
  },
  {
    id: "hacia-estacion",
    prep: "hacia",
    use: "destino",
    fill: "hacia la",
    before: "Caminamos ",
    after: " estación.",
    pt: "Caminhamos em direção à estação.",
    why: "hacia + la: em direção a.",
  },
  {
    id: "segun-mapa",
    prep: "según",
    use: "fonte",
    fill: "según el",
    before: "",
    after: " mapa, es aquí.",
    pt: "Segundo o mapa, é aqui.",
    why: "según + el: de acordo com.",
    aliases: ["segun el"],
  },
  {
    id: "a-ti",
    prep: "a",
    use: "pessoa",
    before: "Te veo ",
    after: " ti en la estación.",
    pt: "Te vejo a você na estação.",
    why: "a + pronome tônico: a ti, a mí.",
  },
  {
    id: "por-eso",
    prep: "por",
    use: "causa",
    before: "Perdí el autobús, ",
    after: " eso llegué tarde.",
    pt: "Perdi o ônibus, por isso cheguei atrasado.",
    why: "por eso = por isso.",
  },
  {
    id: "para-mi",
    prep: "para",
    use: "opinião",
    before: "",
    after: " mí, este café es el mejor.",
    pt: "Para mim, este café é o melhor.",
    why: "Opinião: para mí.",
  },
  {
    id: "por-la-noche",
    prep: "por",
    use: "tempo",
    fill: "por la",
    before: "Leo ",
    after: " noche.",
    pt: "Leio à noite.",
    why: "por la noche / tarde / mañana.",
  },
  {
    id: "por-la-calle",
    prep: "por",
    use: "caminho",
    fill: "por la",
    before: "Caminamos ",
    after: " calle.",
    pt: "Caminhamos pela rua.",
    why: "por + la: ao longo de um lugar.",
  },
  {
    id: "en-el-centro",
    prep: "en",
    use: "lugar",
    fill: "en el",
    before: "Vivo ",
    after: " centro.",
    pt: "Moro no centro.",
    why: "en + el: lugar parado, masculino.",
  },
  {
    id: "en-la-oficina",
    prep: "en",
    use: "lugar",
    fill: "en la",
    before: "Hoy estoy ",
    after: " oficina.",
    pt: "Hoje estou no escritório.",
    why: "en + la: estar em um lugar.",
  },
  {
    id: "en-el-sofa",
    prep: "en",
    use: "lugar",
    fill: "en el",
    before: "Me siento ",
    after: " sofá.",
    pt: "Sento-me no sofá.",
    why: "en + el: posição.",
  },
  {
    id: "en-la-biblioteca",
    prep: "en",
    use: "lugar",
    fill: "en la",
    before: "Estudio ",
    after: " biblioteca.",
    pt: "Estudo na biblioteca.",
    why: "en + la: onde a ação acontece.",
  },
  {
    id: "en-el-jardin",
    prep: "en",
    use: "lugar",
    fill: "en el",
    before: "El perro está ",
    after: " jardín.",
    pt: "O cachorro está no jardim.",
    why: "en + el: lugar parado.",
  },
  {
    id: "a-la-universidad",
    prep: "a",
    use: "destino",
    fill: "a la",
    before: "Por la mañana voy ",
    after: " universidad.",
    pt: "De manhã vou à universidade.",
    why: "a + la: direção, feminino.",
  },
  {
    id: "al-super",
    prep: "al",
    use: "destino",
    before: "Voy ",
    after: " supermercado.",
    pt: "Vou ao supermercado.",
    why: "a + el = al.",
    aliases: ["a el"],
  },
  {
    id: "al-bus",
    prep: "al",
    use: "destino",
    before: "Subo ",
    after: " autobús.",
    pt: "Subo no ônibus.",
    why: "subir al autobús: a + el = al.",
    aliases: ["a el"],
  },
  {
    id: "del-aeropuerto",
    prep: "del",
    use: "origem",
    before: "Vengo ",
    after: " aeropuerto.",
    pt: "Venho do aeroporto.",
    why: "de + el = del.",
    aliases: ["de el"],
  },
  {
    id: "de-la-oficina",
    prep: "de",
    use: "origem",
    fill: "de la",
    before: "Salgo ",
    after: " oficina a las cinco.",
    pt: "Saio do escritório às cinco.",
    why: "de + la: sair de um lugar feminino.",
  },
  {
    id: "para-la-nina",
    prep: "para",
    use: "destinatário",
    fill: "para la",
    before: "Este regalo es ",
    after: " niña.",
    pt: "Este presente é para a menina.",
    why: "para + la: destinatário feminino.",
  },
  {
    id: "para-el-jefe",
    prep: "para",
    use: "destinatário",
    fill: "para el",
    before: "El recado es ",
    after: " jefe.",
    pt: "O recado é para o chefe.",
    why: "para + el: destinatário masculino.",
  },
  {
    id: "con-el-jefe",
    prep: "con",
    use: "companhia",
    fill: "con el",
    before: "Hablo ",
    after: " jefe a las diez.",
    pt: "Falo com o chefe às dez.",
    why: "con + el: companhia, masculino.",
  },
  {
    id: "con-la-hermana",
    prep: "con",
    use: "companhia",
    fill: "con la",
    before: "Salgo ",
    after: " hermana.",
    pt: "Saio com a irmã.",
    why: "con + la: companhia, feminino.",
  },
  {
    id: "a-los-ninos",
    prep: "a",
    use: "pessoa",
    fill: "a los",
    before: "Invito ",
    after: " niños a la fiesta.",
    pt: "Convido as crianças para a festa.",
    why: "a + los: direção ou a pessoal no plural.",
  },
  {
    id: "de-los-vecinos",
    prep: "de",
    use: "posse",
    fill: "de los",
    before: "El coche ",
    after: " vecinos es rojo.",
    pt: "O carro dos vizinhos é vermelho.",
    why: "de + los: posse no plural masculino.",
  },
  {
    id: "de-las-llaves",
    prep: "de",
    use: "posse",
    fill: "de las",
    before: "El llavero ",
    after: " llaves está en la mesa.",
    pt: "O chaveiro das chaves está na mesa.",
    why: "de + las: posse no plural feminino.",
  },
  {
    id: "en-los-cajones",
    prep: "en",
    use: "lugar",
    fill: "en los",
    before: "Las fotos están ",
    after: " cajones.",
    pt: "As fotos estão nas gavetas.",
    why: "en + los: lugar parado, plural.",
  },
  {
    id: "en-las-maletas",
    prep: "en",
    use: "lugar",
    fill: "en las",
    before: "Guardo la ropa ",
    after: " maletas.",
    pt: "Guardo a roupa nas malas.",
    why: "en + las: lugar parado, plural feminino.",
  },
  {
    id: "con-los-amigos",
    prep: "con",
    use: "companhia",
    fill: "con los",
    before: "El viernes salgo ",
    after: " amigos.",
    pt: "Sexta saio com os amigos.",
    why: "con + los: companhia no plural.",
  },
  {
    id: "con-las-vecinas",
    prep: "con",
    use: "companhia",
    fill: "con las",
    before: "Hablo ",
    after: " vecinas todos los días.",
    pt: "Falo com as vizinhas todos os dias.",
    why: "con + las: companhia, plural feminino.",
  },
  {
    id: "sin-el-paraguas",
    prep: "sin",
    use: "ausência",
    fill: "sin el",
    before: "Salí ",
    after: " paraguas y me mojé.",
    pt: "Saí sem o guarda-chuva e me molhei.",
    why: "sin + el: sem o objeto.",
  },
  {
    id: "sin-la-toalla",
    prep: "sin",
    use: "ausência",
    fill: "sin la",
    before: "Fui a la playa ",
    after: " toalla.",
    pt: "Fui à praia sem a toalha.",
    why: "sin + la: sem o objeto feminino.",
  },
  {
    id: "sin-los-ninos",
    prep: "sin",
    use: "ausência",
    fill: "sin los",
    before: "Viajamos ",
    after: " niños este año.",
    pt: "Viajamos sem as crianças este ano.",
    why: "sin + los: sem o grupo.",
  },
  {
    id: "sin-las-galletas",
    prep: "sin",
    use: "ausência",
    fill: "sin las",
    before: "El café está ",
    after: " galletas.",
    pt: "O café está sem as bolachas.",
    why: "sin + las: ausência no plural feminino.",
  },
  {
    id: "por-los-bosques",
    prep: "por",
    use: "caminho",
    fill: "por los",
    before: "Paseamos ",
    after: " bosques.",
    pt: "Passeamos pelos bosques.",
    why: "por + los: através de um lugar plural.",
  },
  {
    id: "por-las-calles",
    prep: "por",
    use: "caminho",
    fill: "por las",
    before: "Caminamos ",
    after: " calles del centro.",
    pt: "Caminhamos pelas ruas do centro.",
    why: "por + las: ao longo de um lugar feminino plural.",
  },
  {
    id: "por-las-tardes",
    prep: "por",
    use: "tempo",
    fill: "por las",
    before: "Corro ",
    after: " tardes.",
    pt: "Corro à tarde (nas tardes).",
    why: "por las tardes / mañanas / noches.",
  },
  {
    id: "para-los-ninos",
    prep: "para",
    use: "destinatário",
    fill: "para los",
    before: "Estos juguetes son ",
    after: " niños.",
    pt: "Estes brinquedos são para as crianças.",
    why: "para + los: destinatário plural.",
  },
  {
    id: "para-las-abuelas",
    prep: "para",
    use: "destinatário",
    fill: "para las",
    before: "Estas flores son ",
    after: " abuelas.",
    pt: "Estas flores são para as avós.",
    why: "para + las: destinatário feminino plural.",
  },
  {
    id: "entre-el-cine",
    prep: "entre",
    use: "lugar",
    fill: "entre el",
    before: "El banco está ",
    after: " cine y la plaza.",
    pt: "O banco fica entre o cinema e a praça.",
    why: "entre + el: entre um lugar masculino e outro.",
  },
  {
    id: "entre-la-plaza",
    prep: "entre",
    use: "lugar",
    fill: "entre la",
    before: "Vivo ",
    after: " plaza y el río.",
    pt: "Moro entre a praça e o rio.",
    why: "entre + la: entre um lugar feminino e outro.",
  },
  {
    id: "entre-los-amigos",
    prep: "entre",
    use: "lugar",
    fill: "entre los",
    before: "Me siento bien ",
    after: " amigos.",
    pt: "Sinto-me bem entre os amigos.",
    why: "entre + los: no meio de um grupo.",
  },
  {
    id: "entre-las-montanas",
    prep: "entre",
    use: "lugar",
    fill: "entre las",
    before: "La casa está ",
    after: " montañas.",
    pt: "A casa fica entre as montanhas.",
    why: "entre + las: no meio de um grupo feminino.",
  },
  {
    id: "hasta-el-lunes",
    prep: "hasta",
    use: "tempo",
    fill: "hasta el",
    before: "El descuento dura ",
    after: " lunes.",
    pt: "O desconto dura até segunda.",
    why: "hasta + el: até um ponto no tempo.",
  },
  {
    id: "hasta-la-noche",
    prep: "hasta",
    use: "tempo",
    fill: "hasta la",
    before: "Hoy trabajo ",
    after: " noche.",
    pt: "Hoje trabalho até a noite.",
    why: "hasta + la: até um limite feminino.",
  },
  {
    id: "hasta-los-finales",
    prep: "hasta",
    use: "tempo",
    fill: "hasta los",
    before: "Leí ",
    after: " últimos capítulos.",
    pt: "Li até os últimos capítulos.",
    why: "hasta + los: até o final de um grupo.",
  },
  {
    id: "desde-el-ano",
    prep: "desde",
    use: "tempo",
    fill: "desde el",
    before: "Vivo aquí ",
    after: " año pasado.",
    pt: "Moro aqui desde o ano passado.",
    why: "desde + el: a partir de um ponto.",
  },
  {
    id: "desde-la-manana",
    prep: "desde",
    use: "tempo",
    fill: "desde la",
    before: "Estoy aquí ",
    after: " mañana.",
    pt: "Estou aqui desde a manhã.",
    why: "desde + la: a partir de um momento feminino.",
  },
  {
    id: "desde-los-seis",
    prep: "desde",
    use: "tempo",
    fill: "desde los",
    before: "Los conozco ",
    after: " seis años.",
    pt: "Conheço-os desde os seis anos.",
    why: "desde + los: a partir de uma idade ou conjunto.",
  },
  {
    id: "sobre-el-sofa",
    prep: "sobre",
    use: "lugar",
    fill: "sobre el",
    before: "El gato está ",
    after: " sofá.",
    pt: "O gato está sobre o sofá.",
    why: "sobre + el: em cima de.",
  },
  {
    id: "sobre-los-problemas",
    prep: "sobre",
    use: "tema",
    fill: "sobre los",
    before: "Hablamos ",
    after: " problemas del trabajo.",
    pt: "Falamos sobre os problemas do trabalho.",
    why: "sobre + los: tema no plural.",
  },
  {
    id: "sobre-las-ballenas",
    prep: "sobre",
    use: "tema",
    fill: "sobre las",
    before: "Vi un documental ",
    after: " ballenas.",
    pt: "Vi um documentário sobre as baleias.",
    why: "sobre + las: tema feminino plural.",
  },
  {
    id: "durante-el-almuerzo",
    prep: "durante",
    use: "tempo",
    fill: "durante el",
    before: "No hablo ",
    after: " almuerzo.",
    pt: "Não falo durante o almoço.",
    why: "durante + el: enquanto isso acontece.",
  },
  {
    id: "durante-los-veranos",
    prep: "durante",
    use: "tempo",
    fill: "durante los",
    before: "Viajamos ",
    after: " veranos.",
    pt: "Viajamos durante os verões.",
    why: "durante + los: ao longo de um período plural.",
  },
  {
    id: "durante-las-vacaciones",
    prep: "durante",
    use: "tempo",
    fill: "durante las",
    before: "Leo mucho ",
    after: " vacaciones.",
    pt: "Leio muito durante as férias.",
    why: "durante + las: ao longo de um período feminino.",
  },
  {
    id: "hacia-el-mar",
    prep: "hacia",
    use: "destino",
    fill: "hacia el",
    before: "Corremos ",
    after: " mar.",
    pt: "Corremos em direção ao mar.",
    why: "hacia + el: em direção a.",
  },
  {
    id: "hacia-los-montes",
    prep: "hacia",
    use: "destino",
    fill: "hacia los",
    before: "El camino va ",
    after: " montes.",
    pt: "O caminho vai em direção aos montes.",
    why: "hacia + los: direção no plural.",
  },
  {
    id: "hacia-las-montanas",
    prep: "hacia",
    use: "destino",
    fill: "hacia las",
    before: "Caminamos ",
    after: " montañas.",
    pt: "Caminhamos em direção às montanhas.",
    why: "hacia + las: direção, feminino plural.",
  },
  {
    id: "segun-la-receta",
    prep: "según",
    use: "fonte",
    fill: "según la",
    before: "",
    after: " receta, lleva huevo.",
    pt: "Segundo a receita, leva ovo.",
    why: "según + la: de acordo com uma fonte feminina.",
    aliases: ["segun la"],
  },
  {
    id: "segun-los-vecinos",
    prep: "según",
    use: "fonte",
    fill: "según los",
    before: "",
    after: " vecinos, llueve mañana.",
    pt: "Segundo os vizinhos, chove amanhã.",
    why: "según + los: de acordo com um grupo.",
    aliases: ["segun los"],
  },
  {
    id: "segun-las-normas",
    prep: "según",
    use: "fonte",
    fill: "según las",
    before: "",
    after: " normas, no se puede fumar.",
    pt: "Segundo as normas, não se pode fumar.",
    why: "según + las: de acordo com regras.",
    aliases: ["segun las"],
  },
];

const ALIASES: Partial<Record<string, string[]>> = {
  al: ["a el"],
  del: ["de el"],
  según: ["segun"],
  "según el": ["segun el"],
};

export function expectedPrep(prompt: PrepPrompt): string {
  return prompt.fill ?? prompt.prep;
}

export function isPrepChunk(prompt: PrepPrompt): boolean {
  const fill = expectedPrep(prompt);
  return fill.includes(" ") || fill === "al" || fill === "del";
}

export function getPrep(id: PrepId): PrepMeta {
  const found = PREPOSITIONS.find((item) => item.id === id);
  if (!found) throw new Error(`Unknown preposition: ${id}`);
  return found;
}

export function promptsForPrep(filter: PrepId | PrepGroupId | "all"): PrepPrompt[] {
  if (filter === "all") return PREP_PROMPTS;
  if (filter === "articulo") return PREP_PROMPTS.filter(isPrepChunk);
  const group = PREP_GROUPS.find((item) => item.id === filter);
  if (group) return PREP_PROMPTS.filter((item) => getPrep(item.prep).group === filter);
  return PREP_PROMPTS.filter((item) => item.prep === filter);
}

export function prepStats(list: PrepPrompt[] = PREP_PROMPTS): { count: number; preps: number } {
  return { count: list.length, preps: new Set(list.map((item) => expectedPrep(item))).size };
}

export function checkPrep(prompt: PrepPrompt, raw: string): CheckResult {
  const expected = expectedPrep(prompt);
  const accepted = [expected, ...(prompt.aliases ?? []), ...(ALIASES[expected] ?? [])].map(normalizeAnswer);
  const given = normalizeAnswer(raw);
  if (!given) return { ok: false, expected, accentOnly: false };
  if (accepted.includes(given)) return { ok: true, expected, accentOnly: false };
  const givenPlain = stripDiacritics(given);
  if (accepted.some((item) => stripDiacritics(item) === givenPlain)) {
    return { ok: true, expected, accentOnly: true };
  }
  return { ok: false, expected, accentOnly: false };
}
