import type { VerbDef } from "./types";

export const VERBS: VerbDef[] = [
  {
    id: "hablar",
    infinitive: "hablar",
    ending: "ar",
    meaningPt: "falar",
    tags: ["regular"],
    usage: "Conversar, falar um idioma, telefonar.",
    examples: [
      { es: "Hablo español todos los días.", pt: "Falo espanhol todos os dias." },
      { es: "¿Hablas con tu hermana?", pt: "Você fala com a sua irmã?" },
    ],
  },
  {
    id: "trabajar",
    infinitive: "trabajar",
    ending: "ar",
    meaningPt: "trabalhar",
    tags: ["regular"],
    usage: "Trabalho, emprego, esforço.",
    examples: [
      { es: "Trabajo en casa los viernes.", pt: "Trabalho em casa às sextas." },
      { es: "Ayer trabajé hasta tarde.", pt: "Ontem trabalhei até tarde." },
    ],
  },
  {
    id: "estudiar",
    infinitive: "estudiar",
    ending: "ar",
    meaningPt: "estudar",
    tags: ["regular"],
    usage: "Estudar, cursar, revisar matéria.",
    examples: [
      { es: "Estudio español por la noche.", pt: "Estudo espanhol à noite." },
      { es: "Estudiamos juntos para el examen.", pt: "Estudamos juntos para a prova." },
    ],
  },
  {
    id: "comprar",
    infinitive: "comprar",
    ending: "ar",
    meaningPt: "comprar",
    tags: ["regular"],
    usage: "Compras, mercado, loja.",
    examples: [
      { es: "Compro pan todas las mañanas.", pt: "Compro pão todas as manhãs." },
      { es: "¿Qué vas a comprar?", pt: "O que você vai comprar?" },
    ],
  },
  {
    id: "llamar",
    infinitive: "llamar",
    ending: "ar",
    meaningPt: "chamar / ligar",
    tags: ["regular"],
    usage: "Chamar alguém, telefonar (llamar por teléfono).",
    examples: [
      { es: "Te llamo esta noche.", pt: "Te ligo esta noite." },
      { es: "¿Cómo te llamas?", pt: "Como você se chama?" },
    ],
  },
  {
    id: "esperar",
    infinitive: "esperar",
    ending: "ar",
    meaningPt: "esperar",
    tags: ["regular"],
    usage: "Esperar alguém ou esperar que algo aconteça (esperar que + subjuntivo).",
    examples: [
      { es: "Espero el autobús aquí.", pt: "Espero o ônibus aqui." },
      { es: "Espero que vengas mañana.", pt: "Espero que você venha amanhã." },
    ],
  },
  {
    id: "necesitar",
    infinitive: "necesitar",
    ending: "ar",
    meaningPt: "precisar",
    tags: ["regular"],
    usage: "Necessitar de algo ou alguém. Muito usado no dia a dia.",
    examples: [
      { es: "Necesito ayuda, por favor.", pt: "Preciso de ajuda, por favor." },
      { es: "¿Necesitas algo del supermercado?", pt: "Você precisa de algo do supermercado?" },
    ],
  },
  {
    id: "comer",
    infinitive: "comer",
    ending: "er",
    meaningPt: "comer",
    tags: ["regular"],
    usage: "Refeições, comida, restaurante.",
    examples: [
      { es: "Como fruta por la mañana.", pt: "Como fruta de manhã." },
      { es: "Ayer comimos en un restaurante.", pt: "Ontem comemos num restaurante." },
    ],
  },
  {
    id: "beber",
    infinitive: "beber",
    ending: "er",
    meaningPt: "beber",
    tags: ["regular"],
    usage: "Beber água, café, suco.",
    examples: [
      { es: "Bebo mucha agua.", pt: "Bebo muita água." },
      { es: "¿Bebes café o té?", pt: "Você bebe café ou chá?" },
    ],
  },
  {
    id: "aprender",
    infinitive: "aprender",
    ending: "er",
    meaningPt: "aprender",
    tags: ["regular"],
    usage: "Aprender um idioma, uma habilidade.",
    examples: [
      { es: "Aprendo español con práctica.", pt: "Aprendo espanhol com prática." },
      { es: "Aprendimos mucho hoy.", pt: "Aprendemos muito hoje." },
    ],
  },
  {
    id: "leer",
    infinitive: "leer",
    ending: "er",
    meaningPt: "ler",
    tags: ["ortografico"],
    usage: "Ler livros, mensagens, notícias. O i átono vira y: leyó, leyeron, leyendo.",
    examples: [
      { es: "Leo el periódico cada domingo.", pt: "Leio o jornal todo domingo." },
      { es: "Ayer leí un capítulo entero.", pt: "Ontem li um capítulo inteiro." },
    ],
    preterite: {
      yo: "leí",
      tu: "leíste",
      el: "leyó",
      nosotros: "leímos",
      vosotros: "leísteis",
      ellos: "leyeron",
    },
    gerund: "leyendo",
    participle: "leído",
  },
  {
    id: "vivir",
    infinitive: "vivir",
    ending: "ir",
    meaningPt: "viver / morar",
    tags: ["regular"],
    usage: "Morar em um lugar, viver uma experiência.",
    examples: [
      { es: "Vivo en São Paulo.", pt: "Moro em São Paulo." },
      { es: "Vivimos cerca del mar.", pt: "Moramos perto do mar." },
    ],
  },
  {
    id: "escribir",
    infinitive: "escribir",
    ending: "ir",
    meaningPt: "escrever",
    tags: ["participio-irregular"],
    usage: "Escrever mensagens, e-mails, textos. Particípio irregular: escrito.",
    examples: [
      { es: "Escribo un mensaje ahora.", pt: "Escrevo uma mensagem agora." },
      { es: "He escrito tres correos.", pt: "Escrevi (tenho escrito) três e-mails." },
    ],
    participle: "escrito",
  },
  {
    id: "abrir",
    infinitive: "abrir",
    ending: "ir",
    meaningPt: "abrir",
    tags: ["participio-irregular"],
    usage: "Abrir portas, lojas, arquivos. Particípio irregular: abierto.",
    examples: [
      { es: "Abro la ventana por la mañana.", pt: "Abro a janela de manhã." },
      { es: "La tienda abre a las nueve.", pt: "A loja abre às nove." },
    ],
    participle: "abierto",
  },
  {
    id: "llegar",
    infinitive: "llegar",
    ending: "ar",
    meaningPt: "chegar",
    tags: ["ortografico"],
    usage: "Chegar a um lugar. No pretérito yo: llegué (g → gu). Subjuntivo: llegue.",
    examples: [
      { es: "Llego a casa a las siete.", pt: "Chego em casa às sete." },
      { es: "Ayer llegué tarde al trabajo.", pt: "Ontem cheguei tarde no trabalho." },
    ],
    preterite: {
      yo: "llegué",
      tu: "llegaste",
      el: "llegó",
      nosotros: "llegamos",
      vosotros: "llegasteis",
      ellos: "llegaron",
    },
    subjunctive: {
      yo: "llegue",
      tu: "llegues",
      el: "llegue",
      nosotros: "lleguemos",
      vosotros: "lleguéis",
      ellos: "lleguen",
    },
  },
  {
    id: "conocer",
    infinitive: "conocer",
    ending: "er",
    meaningPt: "conhecer",
    tags: ["ortografico"],
    usage: "Conhecer pessoas ou lugares. Yo: conozco (c → zc). Pretérito conocí = conheci pela primeira vez.",
    examples: [
      { es: "Conozco Madrid muy bien.", pt: "Conheço Madrid muito bem." },
      { es: "Ayer conocí a tu hermano.", pt: "Ontem conheci o seu irmão." },
    ],
    present: {
      yo: "conozco",
      tu: "conoces",
      el: "conoce",
      nosotros: "conocemos",
      vosotros: "conocéis",
      ellos: "conocen",
    },
    subjunctive: {
      yo: "conozca",
      tu: "conozcas",
      el: "conozca",
      nosotros: "conozcamos",
      vosotros: "conozcáis",
      ellos: "conozcan",
    },
    imperativeTu: "conoce",
  },
  {
    id: "pedir",
    infinitive: "pedir",
    ending: "ir",
    meaningPt: "pedir / encomendar",
    tags: ["stem-change"],
    usage: "Pedir um favor, pedir comida. Mudança e → i (pido, pidió, pidiendo). Não é o mesmo que preguntar.",
    examples: [
      { es: "Pido un café, por favor.", pt: "Peço um café, por favor." },
      { es: "Ayer pedimos pizza.", pt: "Ontem pedimos pizza." },
    ],
    present: {
      yo: "pido",
      tu: "pides",
      el: "pide",
      nosotros: "pedimos",
      vosotros: "pedís",
      ellos: "piden",
    },
    preterite: {
      yo: "pedí",
      tu: "pediste",
      el: "pidió",
      nosotros: "pedimos",
      vosotros: "pedisteis",
      ellos: "pidieron",
    },
    subjunctive: {
      yo: "pida",
      tu: "pidas",
      el: "pida",
      nosotros: "pidamos",
      vosotros: "pidáis",
      ellos: "pidan",
    },
    gerund: "pidiendo",
    participle: "pedido",
    imperativeTu: "pide",
  },
  {
    id: "pensar",
    infinitive: "pensar",
    ending: "ar",
    meaningPt: "pensar",
    tags: ["stem-change"],
    usage: "Pensar, achar. Mudança e → ie (pienso, piensa). Pensar en = pensar em.",
    examples: [
      { es: "Pienso en ti.", pt: "Penso em você." },
      { es: "¿Qué piensas de esto?", pt: "O que você acha disso?" },
    ],
    present: {
      yo: "pienso",
      tu: "piensas",
      el: "piensa",
      nosotros: "pensamos",
      vosotros: "pensáis",
      ellos: "piensan",
    },
    subjunctive: {
      yo: "piense",
      tu: "pienses",
      el: "piense",
      nosotros: "pensemos",
      vosotros: "penséis",
      ellos: "piensen",
    },
    imperativeTu: "piensa",
  },
  {
    id: "empezar",
    infinitive: "empezar",
    ending: "ar",
    meaningPt: "começar",
    tags: ["stem-change"],
    usage: "Começar. e → ie (empiezo) e z → c na yo do pretérito (empecé) e no subjuntivo (empiece).",
    examples: [
      { es: "Empiezo a trabajar a las nueve.", pt: "Começo a trabalhar às nove." },
      { es: "La clase empezó tarde.", pt: "A aula começou tarde." },
    ],
    present: {
      yo: "empiezo",
      tu: "empiezas",
      el: "empieza",
      nosotros: "empezamos",
      vosotros: "empezáis",
      ellos: "empiezan",
    },
    preterite: {
      yo: "empecé",
      tu: "empezaste",
      el: "empezó",
      nosotros: "empezamos",
      vosotros: "empezasteis",
      ellos: "empezaron",
    },
    subjunctive: {
      yo: "empiece",
      tu: "empieces",
      el: "empiece",
      nosotros: "empecemos",
      vosotros: "empecéis",
      ellos: "empiecen",
    },
    imperativeTu: "empieza",
  },
  {
    id: "volver",
    infinitive: "volver",
    ending: "er",
    meaningPt: "voltar",
    tags: ["stem-change"],
    usage: "Voltar. o → ue (vuelvo). Particípio irregular: vuelto. Volver a + inf. = fazer de novo.",
    examples: [
      { es: "Vuelvo a casa a las seis.", pt: "Volto para casa às seis." },
      { es: "¿Has vuelto ya?", pt: "Você já voltou?" },
    ],
    present: {
      yo: "vuelvo",
      tu: "vuelves",
      el: "vuelve",
      nosotros: "volvemos",
      vosotros: "volvéis",
      ellos: "vuelven",
    },
    subjunctive: {
      yo: "vuelva",
      tu: "vuelvas",
      el: "vuelva",
      nosotros: "volvamos",
      vosotros: "volváis",
      ellos: "vuelvan",
    },
    gerund: "volviendo",
    participle: "vuelto",
    imperativeTu: "vuelve",
  },
  {
    id: "dormir",
    infinitive: "dormir",
    ending: "ir",
    meaningPt: "dormir",
    tags: ["stem-change"],
    usage: "Dormir. o → ue no presente (duermo); o → u na 3ª pessoa do pretérito (durmió) e no gerúndio (durmiendo).",
    examples: [
      { es: "Duermo ocho horas.", pt: "Durmo oito horas." },
      { es: "Anoche dormí muy bien.", pt: "Ontem à noite dormi muito bem." },
    ],
    present: {
      yo: "duermo",
      tu: "duermes",
      el: "duerme",
      nosotros: "dormimos",
      vosotros: "dormís",
      ellos: "duermen",
    },
    preterite: {
      yo: "dormí",
      tu: "dormiste",
      el: "durmió",
      nosotros: "dormimos",
      vosotros: "dormisteis",
      ellos: "durmieron",
    },
    subjunctive: {
      yo: "duerma",
      tu: "duermas",
      el: "duerma",
      nosotros: "durmamos",
      vosotros: "durmáis",
      ellos: "duerman",
    },
    gerund: "durmiendo",
    participle: "dormido",
    imperativeTu: "duerme",
  },
  {
    id: "ser",
    infinitive: "ser",
    ending: "er",
    meaningPt: "ser",
    tags: ["irregular"],
    usage: "Identidade, origem, hora, profissão, características permanentes. Não confundir com estar.",
    examples: [
      { es: "Soy brasileño.", pt: "Sou brasileiro." },
      { es: "Ella es médica.", pt: "Ela é médica." },
    ],
    present: {
      yo: "soy",
      tu: "eres",
      el: "es",
      nosotros: "somos",
      vosotros: "sois",
      ellos: "son",
    },
    preterite: {
      yo: "fui",
      tu: "fuiste",
      el: "fue",
      nosotros: "fuimos",
      vosotros: "fuisteis",
      ellos: "fueron",
    },
    imperfect: {
      yo: "era",
      tu: "eras",
      el: "era",
      nosotros: "éramos",
      vosotros: "erais",
      ellos: "eran",
    },
    subjunctive: {
      yo: "sea",
      tu: "seas",
      el: "sea",
      nosotros: "seamos",
      vosotros: "seáis",
      ellos: "sean",
    },
    gerund: "siendo",
    participle: "sido",
    imperativeTu: "sé",
    imperativeVosotros: "sed",
  },
  {
    id: "estar",
    infinitive: "estar",
    ending: "ar",
    meaningPt: "estar",
    tags: ["irregular"],
    usage: "Estado temporário, localização, emoção, resultado. Com gerúndio: estoy hablando.",
    examples: [
      { es: "Estoy cansado hoy.", pt: "Estou cansado hoje." },
      { es: "Estamos en casa.", pt: "Estamos em casa." },
    ],
    present: {
      yo: "estoy",
      tu: "estás",
      el: "está",
      nosotros: "estamos",
      vosotros: "estáis",
      ellos: "están",
    },
    preterite: {
      yo: "estuve",
      tu: "estuviste",
      el: "estuvo",
      nosotros: "estuvimos",
      vosotros: "estuvisteis",
      ellos: "estuvieron",
    },
    subjunctive: {
      yo: "esté",
      tu: "estés",
      el: "esté",
      nosotros: "estemos",
      vosotros: "estéis",
      ellos: "estén",
    },
    gerund: "estando",
    participle: "estado",
    imperativeTu: "está",
  },
  {
    id: "ir",
    infinitive: "ir",
    ending: "ir",
    meaningPt: "ir",
    tags: ["irregular"],
    usage: "Deslocamento. Ir a + infinitivo = futuro próximo (voy a comer). Pretérito igual ao de ser.",
    examples: [
      { es: "Voy al mercado.", pt: "Vou ao mercado." },
      { es: "Ayer fuimos al cine.", pt: "Ontem fomos ao cinema." },
    ],
    present: {
      yo: "voy",
      tu: "vas",
      el: "va",
      nosotros: "vamos",
      vosotros: "vais",
      ellos: "van",
    },
    preterite: {
      yo: "fui",
      tu: "fuiste",
      el: "fue",
      nosotros: "fuimos",
      vosotros: "fuisteis",
      ellos: "fueron",
    },
    imperfect: {
      yo: "iba",
      tu: "ibas",
      el: "iba",
      nosotros: "íbamos",
      vosotros: "ibais",
      ellos: "iban",
    },
    subjunctive: {
      yo: "vaya",
      tu: "vayas",
      el: "vaya",
      nosotros: "vayamos",
      vosotros: "vayáis",
      ellos: "vayan",
    },
    gerund: "yendo",
    participle: "ido",
    imperativeTu: "ve",
    imperativeVosotros: "id",
    imperativeNosotros: "vamos",
    aliases: {
      imperativo: { nosotros: ["vamos", "vayamos"] },
    },
  },
  {
    id: "tener",
    infinitive: "tener",
    ending: "er",
    meaningPt: "ter",
    tags: ["irregular"],
    usage: "Posse, idade, fome/sede (tener hambre). Tener que + inf. = ter que.",
    examples: [
      { es: "Tengo dos hermanos.", pt: "Tenho dois irmãos." },
      { es: "¿Tienes hambre?", pt: "Você está com fome?" },
    ],
    present: {
      yo: "tengo",
      tu: "tienes",
      el: "tiene",
      nosotros: "tenemos",
      vosotros: "tenéis",
      ellos: "tienen",
    },
    preterite: {
      yo: "tuve",
      tu: "tuviste",
      el: "tuvo",
      nosotros: "tuvimos",
      vosotros: "tuvisteis",
      ellos: "tuvieron",
    },
    subjunctive: {
      yo: "tenga",
      tu: "tengas",
      el: "tenga",
      nosotros: "tengamos",
      vosotros: "tengáis",
      ellos: "tengan",
    },
    futureStem: "tendr",
    gerund: "teniendo",
    participle: "tenido",
    imperativeTu: "ten",
  },
  {
    id: "hacer",
    infinitive: "hacer",
    ending: "er",
    meaningPt: "fazer",
    tags: ["irregular"],
    usage: "Fazer, clima (hace frío), tempo (hace dos años).",
    examples: [
      { es: "Hago la cena a las ocho.", pt: "Faço o jantar às oito." },
      { es: "Ayer hice ejercicio.", pt: "Ontem fiz exercício." },
    ],
    present: {
      yo: "hago",
      tu: "haces",
      el: "hace",
      nosotros: "hacemos",
      vosotros: "hacéis",
      ellos: "hacen",
    },
    preterite: {
      yo: "hice",
      tu: "hiciste",
      el: "hizo",
      nosotros: "hicimos",
      vosotros: "hicisteis",
      ellos: "hicieron",
    },
    subjunctive: {
      yo: "haga",
      tu: "hagas",
      el: "haga",
      nosotros: "hagamos",
      vosotros: "hagáis",
      ellos: "hagan",
    },
    futureStem: "har",
    gerund: "haciendo",
    participle: "hecho",
    imperativeTu: "haz",
  },
  {
    id: "poder",
    infinitive: "poder",
    ending: "er",
    meaningPt: "poder / conseguir",
    tags: ["irregular"],
    usage: "Capacidade ou permissão. Stem-changing o→ue no presente (exceto nosotros/vosotros).",
    examples: [
      { es: "Puedo ayudarte mañana.", pt: "Posso te ajudar amanhã." },
      { es: "No pude ir ayer.", pt: "Não pude ir ontem." },
    ],
    present: {
      yo: "puedo",
      tu: "puedes",
      el: "puede",
      nosotros: "podemos",
      vosotros: "podéis",
      ellos: "pueden",
    },
    preterite: {
      yo: "pude",
      tu: "pudiste",
      el: "pudo",
      nosotros: "pudimos",
      vosotros: "pudisteis",
      ellos: "pudieron",
    },
    subjunctive: {
      yo: "pueda",
      tu: "puedas",
      el: "pueda",
      nosotros: "podamos",
      vosotros: "podáis",
      ellos: "puedan",
    },
    futureStem: "podr",
    gerund: "pudiendo",
    participle: "podido",
  },
  {
    id: "querer",
    infinitive: "querer",
    ending: "er",
    meaningPt: "querer / amar",
    tags: ["irregular"],
    usage: "Desejo (quiero café) e afeto (te quiero). Stem-changing e→ie. Pretérito: quise = quis / tentei.",
    examples: [
      { es: "Quiero aprender más.", pt: "Quero aprender mais." },
      { es: "Te quiero mucho.", pt: "Te amo / gosto muito de você." },
    ],
    present: {
      yo: "quiero",
      tu: "quieres",
      el: "quiere",
      nosotros: "queremos",
      vosotros: "queréis",
      ellos: "quieren",
    },
    preterite: {
      yo: "quise",
      tu: "quisiste",
      el: "quiso",
      nosotros: "quisimos",
      vosotros: "quisisteis",
      ellos: "quisieron",
    },
    subjunctive: {
      yo: "quiera",
      tu: "quieras",
      el: "quiera",
      nosotros: "queramos",
      vosotros: "queráis",
      ellos: "quieran",
    },
    futureStem: "querr",
    gerund: "queriendo",
    participle: "querido",
  },
  {
    id: "ver",
    infinitive: "ver",
    ending: "er",
    meaningPt: "ver",
    tags: ["irregular"],
    usage: "Ver, assistir, perceber. Particípio irregular: visto. Imperativo tú: ve (igual ao de ir).",
    examples: [
      { es: "Veo una película esta noche.", pt: "Vou ver um filme esta noite." },
      { es: "¿Has visto mis llaves?", pt: "Você viu minhas chaves?" },
    ],
    present: {
      yo: "veo",
      tu: "ves",
      el: "ve",
      nosotros: "vemos",
      vosotros: "veis",
      ellos: "ven",
    },
    preterite: {
      yo: "vi",
      tu: "viste",
      el: "vio",
      nosotros: "vimos",
      vosotros: "visteis",
      ellos: "vieron",
    },
    imperfect: {
      yo: "veía",
      tu: "veías",
      el: "veía",
      nosotros: "veíamos",
      vosotros: "veíais",
      ellos: "veían",
    },
    subjunctive: {
      yo: "vea",
      tu: "veas",
      el: "vea",
      nosotros: "veamos",
      vosotros: "veáis",
      ellos: "vean",
    },
    gerund: "viendo",
    participle: "visto",
    imperativeTu: "ve",
  },
  {
    id: "dar",
    infinitive: "dar",
    ending: "ar",
    meaningPt: "dar",
    tags: ["irregular"],
    usage: "Dar objetos, dar um passeio (dar un paseo), dar-se conta (darse cuenta).",
    examples: [
      { es: "Te doy mi número.", pt: "Te dou o meu número." },
      { es: "Nos dieron las llaves.", pt: "Nos deram as chaves." },
    ],
    present: {
      yo: "doy",
      tu: "das",
      el: "da",
      nosotros: "damos",
      vosotros: "dais",
      ellos: "dan",
    },
    preterite: {
      yo: "di",
      tu: "diste",
      el: "dio",
      nosotros: "dimos",
      vosotros: "disteis",
      ellos: "dieron",
    },
    subjunctive: {
      yo: "dé",
      tu: "des",
      el: "dé",
      nosotros: "demos",
      vosotros: "deis",
      ellos: "den",
    },
    gerund: "dando",
    participle: "dado",
    imperativeTu: "da",
  },
  {
    id: "decir",
    infinitive: "decir",
    ending: "ir",
    meaningPt: "dizer",
    tags: ["irregular"],
    usage: "Dizer, contar. Pretérito: dije, dijo. Particípio: dicho. Futuro: diré. Imperativo tú: di.",
    examples: [
      { es: "Te digo la verdad.", pt: "Te digo a verdade." },
      { es: "¿Qué me dijiste ayer?", pt: "O que você me disse ontem?" },
    ],
    present: {
      yo: "digo",
      tu: "dices",
      el: "dice",
      nosotros: "decimos",
      vosotros: "decís",
      ellos: "dicen",
    },
    preterite: {
      yo: "dije",
      tu: "dijiste",
      el: "dijo",
      nosotros: "dijimos",
      vosotros: "dijisteis",
      ellos: "dijeron",
    },
    subjunctive: {
      yo: "diga",
      tu: "digas",
      el: "diga",
      nosotros: "digamos",
      vosotros: "digáis",
      ellos: "digan",
    },
    futureStem: "dir",
    gerund: "diciendo",
    participle: "dicho",
    imperativeTu: "di",
  },
  {
    id: "venir",
    infinitive: "venir",
    ending: "ir",
    meaningPt: "vir",
    tags: ["irregular"],
    usage: "Vir. Parecido com tener: vengo, vine, vendré. Imperativo tú: ven.",
    examples: [
      { es: "Vengo del trabajo.", pt: "Venho do trabalho." },
      { es: "¿Vienes con nosotros?", pt: "Você vem com a gente?" },
    ],
    present: {
      yo: "vengo",
      tu: "vienes",
      el: "viene",
      nosotros: "venimos",
      vosotros: "venís",
      ellos: "vienen",
    },
    preterite: {
      yo: "vine",
      tu: "viniste",
      el: "vino",
      nosotros: "vinimos",
      vosotros: "vinisteis",
      ellos: "vinieron",
    },
    subjunctive: {
      yo: "venga",
      tu: "vengas",
      el: "venga",
      nosotros: "vengamos",
      vosotros: "vengáis",
      ellos: "vengan",
    },
    futureStem: "vendr",
    gerund: "viniendo",
    participle: "venido",
    imperativeTu: "ven",
  },
  {
    id: "salir",
    infinitive: "salir",
    ending: "ir",
    meaningPt: "sair",
    tags: ["irregular"],
    usage: "Sair de um lugar, sair com amigos. Yo: salgo. Futuro: saldré. Imperativo tú: sal.",
    examples: [
      { es: "Salgo del trabajo a las cinco.", pt: "Saio do trabalho às cinco." },
      { es: "Esta noche salimos a cenar.", pt: "Esta noite saímos para jantar." },
    ],
    present: {
      yo: "salgo",
      tu: "sales",
      el: "sale",
      nosotros: "salimos",
      vosotros: "salís",
      ellos: "salen",
    },
    subjunctive: {
      yo: "salga",
      tu: "salgas",
      el: "salga",
      nosotros: "salgamos",
      vosotros: "salgáis",
      ellos: "salgan",
    },
    futureStem: "saldr",
    gerund: "saliendo",
    participle: "salido",
    imperativeTu: "sal",
  },
  {
    id: "poner",
    infinitive: "poner",
    ending: "er",
    meaningPt: "pôr / colocar",
    tags: ["irregular"],
    usage: "Colocar, ligar (poner la tele). Pretérito: puse. Particípio: puesto. Imperativo tú: pon.",
    examples: [
      { es: "Pongo la mesa para la cena.", pt: "Arrumo a mesa para o jantar." },
      { es: "¿Dónde pusiste las llaves?", pt: "Onde você pôs as chaves?" },
    ],
    present: {
      yo: "pongo",
      tu: "pones",
      el: "pone",
      nosotros: "ponemos",
      vosotros: "ponéis",
      ellos: "ponen",
    },
    preterite: {
      yo: "puse",
      tu: "pusiste",
      el: "puso",
      nosotros: "pusimos",
      vosotros: "pusisteis",
      ellos: "pusieron",
    },
    subjunctive: {
      yo: "ponga",
      tu: "pongas",
      el: "ponga",
      nosotros: "pongamos",
      vosotros: "pongáis",
      ellos: "pongan",
    },
    futureStem: "pondr",
    gerund: "poniendo",
    participle: "puesto",
    imperativeTu: "pon",
  },
  {
    id: "saber",
    infinitive: "saber",
    ending: "er",
    meaningPt: "saber",
    tags: ["irregular"],
    usage: "Saber um fato ou como fazer. Yo: sé. Pretérito supe = fiquei sabendo. Não confundir com conocer.",
    examples: [
      { es: "Sé hablar un poco de español.", pt: "Sei falar um pouco de espanhol." },
      { es: "No supe la noticia hasta ayer.", pt: "Não fiquei sabendo da notícia até ontem." },
    ],
    present: {
      yo: "sé",
      tu: "sabes",
      el: "sabe",
      nosotros: "sabemos",
      vosotros: "sabéis",
      ellos: "saben",
    },
    preterite: {
      yo: "supe",
      tu: "supiste",
      el: "supo",
      nosotros: "supimos",
      vosotros: "supisteis",
      ellos: "supieron",
    },
    subjunctive: {
      yo: "sepa",
      tu: "sepas",
      el: "sepa",
      nosotros: "sepamos",
      vosotros: "sepáis",
      ellos: "sepan",
    },
    futureStem: "sabr",
    gerund: "sabiendo",
    participle: "sabido",
    imperativeTu: "sabe",
  },
];

export const VERB_GROUPS: { id: string; label: string; match: (v: VerbDef) => boolean }[] = [
  {
    id: "ar",
    label: "Regulares -AR",
    match: (v) => v.ending === "ar" && v.tags.includes("regular"),
  },
  {
    id: "er",
    label: "Regulares -ER",
    match: (v) => v.ending === "er" && v.tags.includes("regular"),
  },
  {
    id: "ir",
    label: "Regulares -IR",
    match: (v) => v.ending === "ir" && v.tags.includes("regular"),
  },
  {
    id: "orto",
    label: "Ortográficos",
    match: (v) =>
      (v.tags.includes("ortografico") || v.tags.includes("participio-irregular")) &&
      !v.tags.includes("stem-change") &&
      !v.tags.includes("irregular"),
  },
  {
    id: "stem",
    label: "Mudança de radical",
    match: (v) => v.tags.includes("stem-change"),
  },
  {
    id: "irr",
    label: "Irregulares essenciais",
    match: (v) => v.tags.includes("irregular"),
  },
];

export function getVerb(id: string): VerbDef {
  const verb = VERBS.find((item) => item.id === id);
  if (!verb) throw new Error(`Unknown verb: ${id}`);
  return verb;
}

export function randomVerb(except?: string): VerbDef {
  const pool = except ? VERBS.filter((v) => v.id !== except) : VERBS;
  return pool[Math.floor(Math.random() * pool.length)] ?? VERBS[0];
}
