import type { VerbDef } from "./types";

export const VERBS: VerbDef[] = [
  {
    id: "hablar",
    infinitive: "hablar",
    ending: "ar",
    meaningPt: "falar",
    tags: ["regular"],
    usage: "Conversar, falar um idioma, telefonar.",
    examples: [
      { es: "Hablo español todos los días.", pt: "Falo espanhol todos os dias." },
      { es: "¿Hablas con tu hermana?", pt: "Você fala com a sua irmã?" },
    ],
  },
  {
    id: "trabajar",
    infinitive: "trabajar",
    ending: "ar",
    meaningPt: "trabalhar",
    tags: ["regular"],
    usage: "Trabalho, emprego, esforço.",
    examples: [
      { es: "Trabajo en casa los viernes.", pt: "Trabalho em casa às sextas." },
      { es: "Ayer trabajé hasta tarde.", pt: "Ontem trabalhei até tarde." },
    ],
  },
  {
    id: "estudiar",
    infinitive: "estudiar",
    ending: "ar",
    meaningPt: "estudar",
    tags: ["regular"],
    usage: "Estudar, cursar, revisar matéria.",
    examples: [
      { es: "Estudio español por la noche.", pt: "Estudo espanhol à noite." },
      { es: "Estudiamos juntos para el examen.", pt: "Estudamos juntos para a prova." },
    ],
  },
  {
    id: "comprar",
    infinitive: "comprar",
    ending: "ar",
    meaningPt: "comprar",
    tags: ["regular"],
    usage: "Compras, mercado, loja.",
    examples: [
      { es: "Compro pan todas las mañanas.", pt: "Compro pão todas as manhãs." },
      { es: "¿Qué vas a comprar?", pt: "O que você vai comprar?" },
    ],
  },
  {
    id: "comer",
    infinitive: "comer",
    ending: "er",
    meaningPt: "comer",
    tags: ["regular"],
    usage: "Refeições, comida, restaurante.",
    examples: [
      { es: "Como fruta por la mañana.", pt: "Como fruta de manhã." },
      { es: "Ayer comimos en un restaurante.", pt: "Ontem comemos num restaurante." },
    ],
  },
  {
    id: "beber",
    infinitive: "beber",
    ending: "er",
    meaningPt: "beber",
    tags: ["regular"],
    usage: "Beber água, café, suco.",
    examples: [
      { es: "Bebo mucha agua.", pt: "Bebo muita água." },
      { es: "¿Bebes café o té?", pt: "Você bebe café ou chá?" },
    ],
  },
  {
    id: "aprender",
    infinitive: "aprender",
    ending: "er",
    meaningPt: "aprender",
    tags: ["regular"],
    usage: "Aprender um idioma, uma habilidade.",
    examples: [
      { es: "Aprendo español con práctica.", pt: "Aprendo espanhol com prática." },
      { es: "Aprendimos mucho hoy.", pt: "Aprendemos muito hoje." },
    ],
  },
  {
    id: "leer",
    infinitive: "leer",
    ending: "er",
    meaningPt: "ler",
    tags: ["ortografico"],
    usage: "Ler livros, mensagens, notícias. O i átono vira y: leyó, leyeron, leyendo.",
    examples: [
      { es: "Leo el periódico cada domingo.", pt: "Leio o jornal todo domingo." },
      { es: "Ayer leí un capítulo entero.", pt: "Ontem li um capítulo inteiro." },
    ],
    preterite: {
      yo: "leí",
      tu: "leíste",
      el: "leyó",
      nosotros: "leímos",
      vosotros: "leísteis",
      ellos: "leyeron",
    },
    gerund: "leyendo",
    participle: "leído",
  },
  {
    id: "vivir",
    infinitive: "vivir",
    ending: "ir",
    meaningPt: "viver / morar",
    tags: ["regular"],
    usage: "Morar em um lugar, viver uma experiência.",
    examples: [
      { es: "Vivo en São Paulo.", pt: "Moro em São Paulo." },
      { es: "Vivimos cerca del mar.", pt: "Moramos perto do mar." },
    ],
  },
  {
    id: "escribir",
    infinitive: "escribir",
    ending: "ir",
    meaningPt: "escrever",
    tags: ["participio-irregular"],
    usage: "Escrever mensagens, e-mails, textos. Particípio irregular: escrito.",
    examples: [
      { es: "Escribo un mensaje ahora.", pt: "Escrevo uma mensagem agora." },
      { es: "He escrito tres correos.", pt: "Escrevi (tenho escrito) três e-mails." },
    ],
    participle: "escrito",
  },
  {
    id: "abrir",
    infinitive: "abrir",
    ending: "ir",
    meaningPt: "abrir",
    tags: ["participio-irregular"],
    usage: "Abrir portas, lojas, arquivos. Particípio irregular: abierto.",
    examples: [
      { es: "Abro la ventana por la mañana.", pt: "Abro a janela de manhã." },
      { es: "La tienda abre a las nueve.", pt: "A loja abre às nove." },
    ],
    participle: "abierto",
  },
  {
    id: "ser",
    infinitive: "ser",
    ending: "er",
    meaningPt: "ser",
    tags: ["irregular"],
    usage: "Identidade, origem, hora, profissão, características permanentes. Não confundir com estar.",
    examples: [
      { es: "Soy brasileño.", pt: "Sou brasileiro." },
      { es: "Ella es médica.", pt: "Ela é médica." },
    ],
    present: {
      yo: "soy",
      tu: "eres",
      el: "es",
      nosotros: "somos",
      vosotros: "sois",
      ellos: "son",
    },
    preterite: {
      yo: "fui",
      tu: "fuiste",
      el: "fue",
      nosotros: "fuimos",
      vosotros: "fuisteis",
      ellos: "fueron",
    },
    imperfect: {
      yo: "era",
      tu: "eras",
      el: "era",
      nosotros: "éramos",
      vosotros: "erais",
      ellos: "eran",
    },
    subjunctive: {
      yo: "sea",
      tu: "seas",
      el: "sea",
      nosotros: "seamos",
      vosotros: "seáis",
      ellos: "sean",
    },
    gerund: "siendo",
    participle: "sido",
    imperativeTu: "sé",
    imperativeVosotros: "sed",
  },
  {
    id: "estar",
    infinitive: "estar",
    ending: "ar",
    meaningPt: "estar",
    tags: ["irregular"],
    usage: "Estado temporário, localização, emoção, resultado. Com gerúndio: estoy hablando.",
    examples: [
      { es: "Estoy cansado hoy.", pt: "Estou cansado hoje." },
      { es: "Estamos en casa.", pt: "Estamos em casa." },
    ],
    present: {
      yo: "estoy",
      tu: "estás",
      el: "está",
      nosotros: "estamos",
      vosotros: "estáis",
      ellos: "están",
    },
    preterite: {
      yo: "estuve",
      tu: "estuviste",
      el: "estuvo",
      nosotros: "estuvimos",
      vosotros: "estuvisteis",
      ellos: "estuvieron",
    },
    subjunctive: {
      yo: "esté",
      tu: "estés",
      el: "esté",
      nosotros: "estemos",
      vosotros: "estéis",
      ellos: "estén",
    },
    gerund: "estando",
    participle: "estado",
    imperativeTu: "está",
  },
  {
    id: "ir",
    infinitive: "ir",
    ending: "ir",
    meaningPt: "ir",
    tags: ["irregular"],
    usage: "Deslocamento. Ir a + infinitivo = futuro próximo (voy a comer). Pretérito igual ao de ser.",
    examples: [
      { es: "Voy al mercado.", pt: "Vou ao mercado." },
      { es: "Ayer fuimos al cine.", pt: "Ontem fomos ao cinema." },
    ],
    present: {
      yo: "voy",
      tu: "vas",
      el: "va",
      nosotros: "vamos",
      vosotros: "vais",
      ellos: "van",
    },
    preterite: {
      yo: "fui",
      tu: "fuiste",
      el: "fue",
      nosotros: "fuimos",
      vosotros: "fuisteis",
      ellos: "fueron",
    },
    imperfect: {
      yo: "iba",
      tu: "ibas",
      el: "iba",
      nosotros: "íbamos",
      vosotros: "ibais",
      ellos: "iban",
    },
    subjunctive: {
      yo: "vaya",
      tu: "vayas",
      el: "vaya",
      nosotros: "vayamos",
      vosotros: "vayáis",
      ellos: "vayan",
    },
    gerund: "yendo",
    participle: "ido",
    imperativeTu: "ve",
    imperativeVosotros: "id",
    imperativeNosotros: "vamos",
    aliases: {
      imperativo: { nosotros: ["vamos", "vayamos"] },
    },
  },
  {
    id: "tener",
    infinitive: "tener",
    ending: "er",
    meaningPt: "ter",
    tags: ["irregular"],
    usage: "Posse, idade, fome/sede (tener hambre). Tener que + inf. = ter que.",
    examples: [
      { es: "Tengo dos hermanos.", pt: "Tenho dois irmãos." },
      { es: "¿Tienes hambre?", pt: "Você está com fome?" },
    ],
    present: {
      yo: "tengo",
      tu: "tienes",
      el: "tiene",
      nosotros: "tenemos",
      vosotros: "tenéis",
      ellos: "tienen",
    },
    preterite: {
      yo: "tuve",
      tu: "tuviste",
      el: "tuvo",
      nosotros: "tuvimos",
      vosotros: "tuvisteis",
      ellos: "tuvieron",
    },
    subjunctive: {
      yo: "tenga",
      tu: "tengas",
      el: "tenga",
      nosotros: "tengamos",
      vosotros: "tengáis",
      ellos: "tengan",
    },
    futureStem: "tendr",
    gerund: "teniendo",
    participle: "tenido",
    imperativeTu: "ten",
  },
  {
    id: "hacer",
    infinitive: "hacer",
    ending: "er",
    meaningPt: "fazer",
    tags: ["irregular"],
    usage: "Fazer, clima (hace frío), tempo (hace dos años).",
    examples: [
      { es: "Hago la cena a las ocho.", pt: "Faço o jantar às oito." },
      { es: "Ayer hice ejercicio.", pt: "Ontem fiz exercício." },
    ],
    present: {
      yo: "hago",
      tu: "haces",
      el: "hace",
      nosotros: "hacemos",
      vosotros: "hacéis",
      ellos: "hacen",
    },
    preterite: {
      yo: "hice",
      tu: "hiciste",
      el: "hizo",
      nosotros: "hicimos",
      vosotros: "hicisteis",
      ellos: "hicieron",
    },
    subjunctive: {
      yo: "haga",
      tu: "hagas",
      el: "haga",
      nosotros: "hagamos",
      vosotros: "hagáis",
      ellos: "hagan",
    },
    futureStem: "har",
    gerund: "haciendo",
    participle: "hecho",
    imperativeTu: "haz",
  },
  {
    id: "poder",
    infinitive: "poder",
    ending: "er",
    meaningPt: "poder / conseguir",
    tags: ["irregular"],
    usage: "Capacidade ou permissão. Stem-changing o→ue no presente (exceto nosotros/vosotros).",
    examples: [
      { es: "Puedo ayudarte mañana.", pt: "Posso te ajudar amanhã." },
      { es: "No pude ir ayer.", pt: "Não pude ir ontem." },
    ],
    present: {
      yo: "puedo",
      tu: "puedes",
      el: "puede",
      nosotros: "podemos",
      vosotros: "podéis",
      ellos: "pueden",
    },
    preterite: {
      yo: "pude",
      tu: "pudiste",
      el: "pudo",
      nosotros: "pudimos",
      vosotros: "pudisteis",
      ellos: "pudieron",
    },
    subjunctive: {
      yo: "pueda",
      tu: "puedas",
      el: "pueda",
      nosotros: "podamos",
      vosotros: "podáis",
      ellos: "puedan",
    },
    futureStem: "podr",
    gerund: "pudiendo",
    participle: "podido",
  },
  {
    id: "querer",
    infinitive: "querer",
    ending: "er",
    meaningPt: "querer / amar",
    tags: ["irregular"],
    usage: "Desejo (quiero café) e afeto (te quiero). Stem-changing e→ie. Pretérito: quise = quis / tentei.",
    examples: [
      { es: "Quiero aprender más.", pt: "Quero aprender mais." },
      { es: "Te quiero mucho.", pt: "Te amo / gosto muito de você." },
    ],
    present: {
      yo: "quiero",
      tu: "quieres",
      el: "quiere",
      nosotros: "queremos",
      vosotros: "queréis",
      ellos: "quieren",
    },
    preterite: {
      yo: "quise",
      tu: "quisiste",
      el: "quiso",
      nosotros: "quisimos",
      vosotros: "quisisteis",
      ellos: "quisieron",
    },
    subjunctive: {
      yo: "quiera",
      tu: "quieras",
      el: "quiera",
      nosotros: "queramos",
      vosotros: "queráis",
      ellos: "quieran",
    },
    futureStem: "querr",
    gerund: "queriendo",
    participle: "querido",
  },
  {
    id: "ver",
    infinitive: "ver",
    ending: "er",
    meaningPt: "ver",
    tags: ["irregular"],
    usage: "Ver, assistir, perceber. Particípio irregular: visto. Imperativo tú: ve (igual ao de ir).",
    examples: [
      { es: "Veo una película esta noche.", pt: "Vou ver um filme esta noite." },
      { es: "¿Has visto mis llaves?", pt: "Você viu minhas chaves?" },
    ],
    present: {
      yo: "veo",
      tu: "ves",
      el: "ve",
      nosotros: "vemos",
      vosotros: "veis",
      ellos: "ven",
    },
    preterite: {
      yo: "vi",
      tu: "viste",
      el: "vio",
      nosotros: "vimos",
      vosotros: "visteis",
      ellos: "vieron",
    },
    imperfect: {
      yo: "veía",
      tu: "veías",
      el: "veía",
      nosotros: "veíamos",
      vosotros: "veíais",
      ellos: "veían",
    },
    subjunctive: {
      yo: "vea",
      tu: "veas",
      el: "vea",
      nosotros: "veamos",
      vosotros: "veáis",
      ellos: "vean",
    },
    gerund: "viendo",
    participle: "visto",
    imperativeTu: "ve",
  },
  {
    id: "dar",
    infinitive: "dar",
    ending: "ar",
    meaningPt: "dar",
    tags: ["irregular"],
    usage: "Dar objetos, dar um passeio (dar un paseo), dar-se conta (darse cuenta).",
    examples: [
      { es: "Te doy mi número.", pt: "Te dou o meu número." },
      { es: "Nos dieron las llaves.", pt: "Nos deram as chaves." },
    ],
    present: {
      yo: "doy",
      tu: "das",
      el: "da",
      nosotros: "damos",
      vosotros: "dais",
      ellos: "dan",
    },
    preterite: {
      yo: "di",
      tu: "diste",
      el: "dio",
      nosotros: "dimos",
      vosotros: "disteis",
      ellos: "dieron",
    },
    subjunctive: {
      yo: "dé",
      tu: "des",
      el: "dé",
      nosotros: "demos",
      vosotros: "deis",
      ellos: "den",
    },
    gerund: "dando",
    participle: "dado",
    imperativeTu: "da",
  },
];

export const VERB_GROUPS: { id: string; label: string; match: (v: VerbDef) => boolean }[] = [
  {
    id: "ar",
    label: "Regulares -AR",
    match: (v) => v.ending === "ar" && v.tags.includes("regular"),
  },
  {
    id: "er",
    label: "Regulares -ER",
    match: (v) => v.ending === "er" && v.tags.includes("regular"),
  },
  {
    id: "ir",
    label: "Regulares -IR",
    match: (v) => v.ending === "ir" && v.tags.includes("regular"),
  },
  {
    id: "orto",
    label: "Ortográficos",
    match: (v) => v.tags.includes("ortografico") || v.tags.includes("participio-irregular"),
  },
  {
    id: "irr",
    label: "Irregulares essenciais",
    match: (v) => v.tags.includes("irregular"),
  },
];

export function getVerb(id: string): VerbDef {
  const verb = VERBS.find((item) => item.id === id);
  if (!verb) throw new Error(`Unknown verb: ${id}`);
  return verb;
}

export function randomVerb(except?: string): VerbDef {
  const pool = except ? VERBS.filter((v) => v.id !== except) : VERBS;
  return pool[Math.floor(Math.random() * pool.length)] ?? VERBS[0];
}
